<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.39">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>2&nbsp; Statistical Due Diligence – S4BTC</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./03-regime-research.html" rel="next">
<link href="./01-architecture.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-0626ff4d7a71b55c8707dcae1d04a9b6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-0f1d7832f862a9a05de4b1f937104ab7.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


</head>

<body class="nav-sidebar floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">S4BTC</span>
    </a>
  </div>
        <div class="quarto-navbar-tools tools-end">
    <a href="https://github.com/erictvillarreal/RoboTrader812" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
          <div id="quarto-search" class="" title="Search"></div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./02-statistical-due-diligence.html"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Statistical Due Diligence</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Executive Summary</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-architecture.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">System Architecture</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-statistical-due-diligence.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Statistical Due Diligence</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-regime-research.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Regime Research</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-live-validation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Live Validation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-deployment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Deployment</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-roadmap.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Roadmap — Open Gaps</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./99-appendix-data-sources.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Appendix — Data Source Reconciliation</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#objective" id="toc-objective" class="nav-link active" data-scroll-target="#objective"><span class="header-section-number">2.1</span> Objective</a></li>
  <li><a href="#baseline-system-snapshot" id="toc-baseline-system-snapshot" class="nav-link" data-scroll-target="#baseline-system-snapshot"><span class="header-section-number">2.2</span> Baseline System Snapshot</a></li>
  <li><a href="#priority-1---probability-calibration-audit" id="toc-priority-1---probability-calibration-audit" class="nav-link" data-scroll-target="#priority-1---probability-calibration-audit"><span class="header-section-number">2.3</span> Priority 1 - Probability Calibration Audit</a></li>
  <li><a href="#priority-2---regime-segmentation" id="toc-priority-2---regime-segmentation" class="nav-link" data-scroll-target="#priority-2---regime-segmentation"><span class="header-section-number">2.4</span> Priority 2 - Regime Segmentation</a></li>
  <li><a href="#priority-3---reality-modeling-friction-stress-test" id="toc-priority-3---reality-modeling-friction-stress-test" class="nav-link" data-scroll-target="#priority-3---reality-modeling-friction-stress-test"><span class="header-section-number">2.5</span> Priority 3 - Reality Modeling (Friction Stress Test)</a></li>
  <li><a href="#priority-4---position-sizing-research" id="toc-priority-4---position-sizing-research" class="nav-link" data-scroll-target="#priority-4---position-sizing-research"><span class="header-section-number">2.6</span> Priority 4 - Position Sizing Research</a></li>
  <li><a href="#priority-5---randomized-label-sanity-check" id="toc-priority-5---randomized-label-sanity-check" class="nav-link" data-scroll-target="#priority-5---randomized-label-sanity-check"><span class="header-section-number">2.7</span> Priority 5 - Randomized Label Sanity Check</a></li>
  <li><a href="#priority-6---trade-dependency-analysis" id="toc-priority-6---trade-dependency-analysis" class="nav-link" data-scroll-target="#priority-6---trade-dependency-analysis"><span class="header-section-number">2.8</span> Priority 6 - Trade Dependency Analysis</a></li>
  <li><a href="#priority-7---whites-reality-check-spa" id="toc-priority-7---whites-reality-check-spa" class="nav-link" data-scroll-target="#priority-7---whites-reality-check-spa"><span class="header-section-number">2.9</span> Priority 7 - White’s Reality Check / SPA</a></li>
  <li><a href="#feature-significance-stability" id="toc-feature-significance-stability" class="nav-link" data-scroll-target="#feature-significance-stability"><span class="header-section-number">2.10</span> Feature Significance / Stability</a></li>
  <li><a href="#monte-carlo-analysis" id="toc-monte-carlo-analysis" class="nav-link" data-scroll-target="#monte-carlo-analysis"><span class="header-section-number">2.11</span> Monte Carlo Analysis</a></li>
  <li><a href="#final-conclusions-per-statisticsreadme.md" id="toc-final-conclusions-per-statisticsreadme.md" class="nav-link" data-scroll-target="#final-conclusions-per-statisticsreadme.md"><span class="header-section-number">2.12</span> Final Conclusions (per statistics/README.md)</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/erictvillarreal/RoboTrader812/edit/main/02-statistical-due-diligence.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/erictvillarreal/RoboTrader812/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Statistical Due Diligence</span></h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="objective" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="objective"><span class="header-section-number">2.1</span> Objective</h2>
<p>Full institutional-grade statistical due diligence over the S4BTC engine before live deployment, leverage scaling, or external capital allocation. Source: statistics/README.md.</p>
<p>Questions this audit answers:</p>
<ol type="1">
<li>Does the strategy possess statistically significant edge?</li>
<li>Is the edge robust across regimes?</li>
<li>Is the system overfit?</li>
<li>Can the strategy survive realistic market frictions?</li>
<li>Is the edge scalable with leverage and sizing?</li>
<li>Can the edge survive randomized sanity tests?</li>
<li>Does the strategy exhibit conditional alpha or structural alpha?</li>
</ol>
</section>
<section id="baseline-system-snapshot" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="baseline-system-snapshot"><span class="header-section-number">2.2</span> Baseline System Snapshot</h2>
<p>Dataset: BTCUSDT 1H, ~33,140 observations, 2022-2026. Walk-forward: 180-day rolling train window, 14-day test step, EV-based trade selection, leverage-aware risk constraints.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Metric</th>
<th>Value (per statistics/README.md)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Final Equity</td>
<td>$7,989</td>
</tr>
<tr class="even">
<td>Starting Equity</td>
<td>$1,000</td>
</tr>
<tr class="odd">
<td>CAGR</td>
<td>~72%</td>
</tr>
<tr class="even">
<td>Winrate</td>
<td>64.65%</td>
</tr>
<tr class="odd">
<td>Trades</td>
<td>2,968</td>
</tr>
<tr class="even">
<td>Mean Accuracy</td>
<td>61.63%</td>
</tr>
<tr class="odd">
<td>Mean F1</td>
<td>0.218</td>
</tr>
<tr class="even">
<td>Mean Precision</td>
<td>0.286</td>
</tr>
<tr class="odd">
<td>Mean Recall</td>
<td>0.266</td>
</tr>
<tr class="even">
<td>Max Drawdown (Daily)</td>
<td>-2.04%</td>
</tr>
<tr class="odd">
<td>Max Drawdown (Intraday)</td>
<td>-2.14%</td>
</tr>
<tr class="even">
<td>Worst Daily Return</td>
<td>-0.40%</td>
</tr>
</tbody>
</table>
<p>Note: these figures differ from walk_summary.json (a later run). See Appendix - Data Reconciliation. Flagged, not yet resolved.</p>
</section>
<section id="priority-1---probability-calibration-audit" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="priority-1---probability-calibration-audit"><span class="header-section-number">2.3</span> Priority 1 - Probability Calibration Audit</h2>
<p>Objective: validate whether predicted probabilities correspond to realized outcomes: detect overconfidence, probability drift, threshold distortion, false certainty.</p>
<p>Files: calibration.py, calibration_table.csv, reliability_diagram.png, probability_sharpness.png, confidence_analysis.csv.</p>
<p>Finding: predicted probabilities were overconfident. High-confidence predictions did not translate into proportionally higher realized winrates; confidence bins clustered near 0.50.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Avg Confidence</th>
<th>Realized Winrate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0.49</td>
<td>0.23</td>
</tr>
<tr class="even">
<td>0.47</td>
<td>0.30</td>
</tr>
<tr class="odd">
<td>0.45</td>
<td>0.28</td>
</tr>
</tbody>
</table>
<div id="fig-reliability" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-reliability-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/reliability_diagram.png" class="img-fluid figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-reliability-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.1: Reliability diagram: predicted confidence vs.&nbsp;realized winrate, showing systematic overconfidence.
</figcaption>
</figure>
</div>
<div id="fig-sharpness" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sharpness-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/probability_sharpness.png" class="img-fluid figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sharpness-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.2: Probability sharpness: distribution of predicted probabilities, clustered near 0.50.
</figcaption>
</figure>
</div>
<p>Recalibration study (s4_enhancement/probabilistic_recalibration.py):</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Model</th>
<th>Brier</th>
<th>LogLoss</th>
<th>F1</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>RAW</td>
<td>0.292</td>
<td>1.031</td>
<td>0.269</td>
</tr>
<tr class="even">
<td>ISOTONIC</td>
<td>0.211</td>
<td>1.121</td>
<td>0.0005</td>
</tr>
<tr class="odd">
<td>PLATT</td>
<td>0.210</td>
<td>1.115</td>
<td>0.0000</td>
</tr>
</tbody>
</table>
<p>Interpretation: recalibration improved Brier score and probability consistency, but destroyed F1 classification performance. Probabilities became statistically smoother but thresholds became invalid. Future work requires EV-aware thresholds, percentile thresholds, dynamic decision boundaries, calibration-aware walk-forward integration - not literal-probability thresholds.</p>
</section>
<section id="priority-2---regime-segmentation" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="priority-2---regime-segmentation"><span class="header-section-number">2.4</span> Priority 2 - Regime Segmentation</h2>
<p>Objective: determine where the edge exists, where it disappears, when the strategy should deactivate.</p>
<p>Files: regime_segmentation.py, regime_volatility.csv, trend_regime_segmentation.py, trend_regime_report.csv, dma200_report.csv, regime_analysis.py, regime_report.csv.</p>
<p>Volatility regimes:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Regime</th>
<th>Winrate</th>
<th>Avg Return</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Q4_HIGH</td>
<td>64.15%</td>
<td>1.24%</td>
</tr>
<tr class="even">
<td>Q3_MEDHIGH</td>
<td>67.03%</td>
<td>0.87%</td>
</tr>
<tr class="odd">
<td>Q2_MEDLOW</td>
<td>63.55%</td>
<td>0.59%</td>
</tr>
<tr class="even">
<td>Q1_LOW</td>
<td>64.45%</td>
<td>0.36%</td>
</tr>
</tbody>
</table>
<p>Trend regimes:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Regime</th>
<th>Winrate</th>
<th>Avg Return</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>BULL_TREND</td>
<td>67.38%</td>
<td>0.85%</td>
</tr>
<tr class="even">
<td>BEAR_TREND</td>
<td>64.08%</td>
<td>0.74%</td>
</tr>
<tr class="odd">
<td>BULL_WEAK</td>
<td>64.90%</td>
<td>0.72%</td>
</tr>
<tr class="even">
<td>BEAR_RALLY</td>
<td>56.77%</td>
<td>0.56%</td>
</tr>
</tbody>
</table>
<p>200 DMA regimes:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Regime</th>
<th>Winrate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>ABOVE_200DMA</td>
<td>66.89%</td>
</tr>
<tr class="even">
<td>BELOW_200DMA</td>
<td>62.52%</td>
</tr>
</tbody>
</table>
<p>Interpretation: the system is not always-on alpha. It behaves as conditional regime alpha: best in bullish trend + above 200DMA + high volatility; worst in bear rallies. This motivated the meta-regime filtering research in Chapter 3.</p>
</section>
<section id="priority-3---reality-modeling-friction-stress-test" class="level2" data-number="2.5">
<h2 data-number="2.5" class="anchored" data-anchor-id="priority-3---reality-modeling-friction-stress-test"><span class="header-section-number">2.5</span> Priority 3 - Reality Modeling (Friction Stress Test)</h2>
<p>Objective: stress-test the system under realistic trading conditions: spread widening, slippage expansion, liquidity degradation, execution friction.</p>
<p>Files: reality_modeling.py, reality_modeling_report.csv.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Scenario</th>
<th>Outcome</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>BASELINE</td>
<td>Extremely profitable</td>
</tr>
<tr class="even">
<td>LIGHT_FRICTION</td>
<td>Survived</td>
</tr>
<tr class="odd">
<td>MEDIUM_FRICTION</td>
<td>Survived</td>
</tr>
<tr class="even">
<td>HEAVY_FRICTION</td>
<td>Survived</td>
</tr>
<tr class="odd">
<td>EXTREME_FRICTION</td>
<td>Collapsed</td>
</tr>
</tbody>
</table>
<p>Interpretation: the edge survives realistic execution friction and moderate liquidity degradation, but catastrophic friction destroys profitability. Execution quality remains critical.</p>
</section>
<section id="priority-4---position-sizing-research" class="level2" data-number="2.6">
<h2 data-number="2.6" class="anchored" data-anchor-id="priority-4---position-sizing-research"><span class="header-section-number">2.6</span> Priority 4 - Position Sizing Research</h2>
<p>Objective: determine optimal leverage, Kelly sizing, volatility targeting feasibility.</p>
<p>Files: fractional_kelly_research.py, fractional_kelly_report.csv, vol_targeting_report.csv.</p>
<p>Full Kelly estimate: 0.505 - unusually high for a systematic trading system.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Fraction</th>
<th>Max DD</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0.10 Kelly</td>
<td>-0.78%</td>
</tr>
<tr class="even">
<td>0.25 Kelly</td>
<td>-1.94%</td>
</tr>
<tr class="odd">
<td>0.50 Kelly</td>
<td>-3.84%</td>
</tr>
<tr class="even">
<td>0.75 Kelly</td>
<td>-5.71%</td>
</tr>
<tr class="odd">
<td>1.00 Kelly</td>
<td>-7.54%</td>
</tr>
</tbody>
</table>
<p>Interpretation: the system appears risk-scalable and leverage-tolerant, with Sharpe remaining approximately constant across leverage scaling (near-linear behavior under scaling) - atypical for overfit systems. Full Kelly introduces unnecessary volatility; fractional Kelly dramatically improves survivability.</p>
</section>
<section id="priority-5---randomized-label-sanity-check" class="level2" data-number="2.7">
<h2 data-number="2.7" class="anchored" data-anchor-id="priority-5---randomized-label-sanity-check"><span class="header-section-number">2.7</span> Priority 5 - Randomized Label Sanity Check</h2>
<p>Objective: determine whether the model extracts genuine signal or exploits noise.</p>
<p>Files: randomized_labels_sanity.py, randomized_labels_report.csv.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Metric</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Mean Accuracy</td>
<td>72.9%</td>
</tr>
<tr class="even">
<td>Mean Precision</td>
<td>0.044</td>
</tr>
<tr class="odd">
<td>Mean Recall</td>
<td>0.009</td>
</tr>
<tr class="even">
<td>Mean F1</td>
<td>0.014</td>
</tr>
</tbody>
</table>
<p>Interpretation: when labels were randomized, predictive quality collapsed (F1 near-vanished, recall disappeared). Strong evidence the original model is not simply memorizing noise. High accuracy under randomization is a base-rate artifact (class imbalance), not a signal - F1/recall are the diagnostic metrics here.</p>
</section>
<section id="priority-6---trade-dependency-analysis" class="level2" data-number="2.8">
<h2 data-number="2.8" class="anchored" data-anchor-id="priority-6---trade-dependency-analysis"><span class="header-section-number">2.8</span> Priority 6 - Trade Dependency Analysis</h2>
<p>Objective: study clustering, path dependency, serial correlation, streak behavior.</p>
<p>Files: trade_dependency_analysis.py, trade_dependency_report.csv.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Metric</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Global Winrate</td>
<td>64.79%</td>
</tr>
<tr class="even">
<td>Avg Win Streak</td>
<td>17.94</td>
</tr>
<tr class="odd">
<td>Max Win Streak</td>
<td>120</td>
</tr>
<tr class="even">
<td>Avg Loss Streak</td>
<td>9.75</td>
</tr>
<tr class="odd">
<td>Max Loss Streak</td>
<td>52</td>
</tr>
<tr class="even">
<td>Lag-1 Autocorrelation</td>
<td>0.851</td>
</tr>
</tbody>
</table>
<p>Interpretation: trades exhibit significant clustering, non-random sequencing, and persistent market-state behavior - further support for regime dependence and structural conditional alpha (rather than i.i.d. edge).</p>
</section>
<section id="priority-7---whites-reality-check-spa" class="level2" data-number="2.9">
<h2 data-number="2.9" class="anchored" data-anchor-id="priority-7---whites-reality-check-spa"><span class="header-section-number">2.9</span> Priority 7 - White’s Reality Check / SPA</h2>
<p>Objective: test whether the observed edge survives multiple-testing bias and data-snooping concerns.</p>
<p>Files: whites_reality_check.py, whites_reality_check_report.csv.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Metric</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Observed Mean Return</td>
<td>0.007652</td>
</tr>
<tr class="even">
<td>Std Return</td>
<td>0.011966</td>
</tr>
<tr class="odd">
<td>Sharpe-like</td>
<td>0.6395</td>
</tr>
<tr class="even">
<td>White RC p-value</td>
<td>0.506 (FAIL)</td>
</tr>
<tr class="odd">
<td>SPA Sign-Flip p-value</td>
<td>0.000 (PASS)</td>
</tr>
</tbody>
</table>
<p>Interpretation - mixed result. White’s Reality Check fails (p=0.506), suggesting possible sensitivity to data-mining bias when benchmarked against a large universe of alternatives. The SPA sign-flip approximation passes (p=0.000). This is not definitive proof of edge, but also not a rejection. See Chapter 3 for the regime-conditional SPA re-analysis (BEAR/LATERAL/BULL, all p=0.000 vs buy-and-hold), which explains the global White RC failure as a benchmark-selection artifact (buy-and-hold in BTC’s strongest historical bull run), not model data-snooping.</p>
</section>
<section id="feature-significance-stability" class="level2" data-number="2.10">
<h2 data-number="2.10" class="anchored" data-anchor-id="feature-significance-stability"><span class="header-section-number">2.10</span> Feature Significance / Stability</h2>
<p>Objective: measure feature importance, stability, overfit indicators.</p>
<p>Files: feature_significance.py, feature_significance_full.csv, feature_significance_summary.csv.</p>
<p>Initial finding (XGBoost gain/cover importance): most features displayed unstable importance - volume, MACD derivatives, EMA structures, RSI, ATR all highly unstable. Interpretation: edge may emerge from feature interaction, not single dominant predictors; possible regime dependence; possible need for adaptive models.</p>
<p>Superseding finding (SHAP stability, later session - see Chapter 4): using SHAP instead of XGBoost gain/cover (methodologically superior - SHAP measures actual contribution to output), all features show CV &lt; 0.5 (stability threshold):</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Feature</th>
<th>CV</th>
<th>Status</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>macd_diff</td>
<td>0.169</td>
<td>STABLE</td>
</tr>
<tr class="even">
<td>rsi_14</td>
<td>0.272</td>
<td>STABLE</td>
</tr>
<tr class="odd">
<td>atr</td>
<td>0.275</td>
<td>STABLE</td>
</tr>
<tr class="even">
<td>macd</td>
<td>0.352</td>
<td>STABLE</td>
</tr>
<tr class="odd">
<td>macd_signal</td>
<td>0.359</td>
<td>STABLE</td>
</tr>
<tr class="even">
<td>ema_10</td>
<td>0.373</td>
<td>STABLE</td>
</tr>
<tr class="odd">
<td>ema_30</td>
<td>0.419</td>
<td>STABLE</td>
</tr>
</tbody>
</table>
<p>Ranking by average importance: ema_30 (0.0947, structural anchor) &gt; atr (0.0334) &gt; macd (0.0279) &gt; ema_10 (0.0229) &gt; macd_diff (0.0177) &gt; rsi_14 (0.0126) &gt; macd_signal (0.0084). Notable event: ema_30 importance drops from 0.1005 to 0.0224 in Nov 2024 (post-election ATH breakout), with rsi_14 compensating - interpreted as healthy model adaptation, not fragility.</p>
<p>Note: the original (unstable) finding used XGBoost gain/cover; the later SHAP analysis supersedes it methodologically. Both are kept here since they come from different research sessions and use different feature sets - flagged for reconciliation in the Appendix.</p>
</section>
<section id="monte-carlo-analysis" class="level2" data-number="2.11">
<h2 data-number="2.11" class="anchored" data-anchor-id="monte-carlo-analysis"><span class="header-section-number">2.11</span> Monte Carlo Analysis</h2>
<p>Objective: stress-test return distribution robustness: path variability, probabilistic survivability, drawdown robustness, compounding stability.</p>
<p>Files: montecarlo.py, montecarlo_results.csv, montecarlo_distribution.png, montecarlo_equity_curves.png.</p>
<p>Three methods run: reshuffle, bootstrap, block bootstrap. Sample of results (final equity from $1,000 start, 4 runs shown):</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Method</th>
<th>Sample Final Equity Range</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Reshuffle</td>
<td>~$63,826 (constant across runs - deterministic reshuffle of fixed trade set)</td>
</tr>
<tr class="even">
<td>Bootstrap</td>
<td>$56,253 - $65,236</td>
</tr>
<tr class="odd">
<td>Block Bootstrap</td>
<td>$50,050 - $92,153</td>
</tr>
</tbody>
</table>
<div id="fig-mc-dist" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mc-dist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/montecarlo_distribution.png" class="img-fluid figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mc-dist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.3: Monte Carlo distribution: reshuffle, bootstrap, and block-bootstrap final equity distributions.
</figcaption>
</figure>
</div>
<div id="fig-mc-equity" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mc-equity-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/montecarlo_equity_curves.png" class="img-fluid figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mc-equity-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.4: Monte Carlo equity curves: simulated paths under reshuffle, bootstrap, and block-bootstrap methods.
</figcaption>
</figure>
</div>
<p>Note: these figures are approximately 8x larger than the walk-forward baseline equity ($7,989-$8,590 depending on source). This suggests the Monte Carlo in statistics/ may be running over a different (possibly longer or unfiltered) trade set than the walk-forward baseline - flagged in the Appendix for reconciliation, not yet explained.</p>
</section>
<section id="final-conclusions-per-statisticsreadme.md" class="level2" data-number="2.12">
<h2 data-number="2.12" class="anchored" data-anchor-id="final-conclusions-per-statisticsreadme.md"><span class="header-section-number">2.12</span> Final Conclusions (per statistics/README.md)</h2>
<p>The audit strongly suggests the system likely possesses genuine conditional edge:</p>
<ul>
<li>survives randomized labels,</li>
<li>survives realistic friction,</li>
<li>improves coherently under favorable regimes,</li>
<li>displays structured clustering,</li>
<li>remains profitable under leverage scaling.</li>
</ul>
<p>However, the system is not yet production-grade. Remaining critical tasks: live shadow deployment, calibration-aware walk-forward, dynamic thresholds, funding/perp features, microstructure signals, order-flow integration, live execution validation (see Chapter 6 - Roadmap).</p>
<p>Current classification: “Research-grade promising systematic strategy” - not yet institutional production system, but substantially beyond hobby backtesting.</p>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./01-architecture.html" class="pagination-link" aria-label="System Architecture">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">System Architecture</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./03-regime-research.html" class="pagination-link" aria-label="Regime Research">
        <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Regime Research</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb1" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu"># Statistical Due Diligence</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">## Objective</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>Full institutional-grade statistical due diligence over the S4BTC engine before live deployment, leverage scaling, or external capital allocation. Source: statistics/README.md.</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>Questions this audit answers:</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>Does the strategy possess statistically significant edge?</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>Is the edge robust across regimes?</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>Is the system overfit?</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>Can the strategy survive realistic market frictions?</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span>Is the edge scalable with leverage and sizing?</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="ss">6. </span>Can the edge survive randomized sanity tests?</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="ss">7. </span>Does the strategy exhibit conditional alpha or structural alpha?</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="fu">## Baseline System Snapshot</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>Dataset: BTCUSDT 1H, ~33,140 observations, 2022-2026. Walk-forward: 180-day rolling train window, 14-day test step, EV-based trade selection, leverage-aware risk constraints.</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>| Metric | Value (per statistics/README.md) |</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>|---|---|</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>| Final Equity | $7,989 |</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>| Starting Equity | $1,000 |</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>| CAGR | ~72% |</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>| Winrate | 64.65% |</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>| Trades | 2,968 |</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>| Mean Accuracy | 61.63% |</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>| Mean F1 | 0.218 |</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>| Mean Precision | 0.286 |</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>| Mean Recall | 0.266 |</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>| Max Drawdown (Daily) | -2.04% |</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>| Max Drawdown (Intraday) | -2.14% |</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>| Worst Daily Return | -0.40% |</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>Note: these figures differ from walk_summary.json (a later run). See Appendix - Data Reconciliation. Flagged, not yet resolved.</span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a><span class="fu">## Priority 1 - Probability Calibration Audit</span></span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>Objective: validate whether predicted probabilities correspond to realized outcomes: detect overconfidence, probability drift, threshold distortion, false certainty.</span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a>Files: calibration.py, calibration_table.csv, reliability_diagram.png, probability_sharpness.png, confidence_analysis.csv.</span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a>Finding: predicted probabilities were overconfident. High-confidence predictions did not translate into proportionally higher realized winrates; confidence bins clustered near 0.50.</span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a>| Avg Confidence | Realized Winrate |</span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a>|---|---|</span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a>| 0.49 | 0.23 |</span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a>| 0.47 | 0.30 |</span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a>| 0.45 | 0.28 |</span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a><span class="al">![Reliability diagram: predicted confidence vs. realized winrate, showing systematic overconfidence.](images/reliability_diagram.png)</span>{#fig-reliability width=80%}</span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a><span class="al">![Probability sharpness: distribution of predicted probabilities, clustered near 0.50.](images/probability_sharpness.png)</span>{#fig-sharpness width=80%}</span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a>Recalibration study (s4_enhancement/probabilistic_recalibration.py):</span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a>| Model | Brier | LogLoss | F1 |</span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a>|---|---|---|---|</span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a>| RAW | 0.292 | 1.031 | 0.269 |</span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a>| ISOTONIC | 0.211 | 1.121 | 0.0005 |</span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a>| PLATT | 0.210 | 1.115 | 0.0000 |</span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a>Interpretation: recalibration improved Brier score and probability consistency, but destroyed F1 classification performance. Probabilities became statistically smoother but thresholds became invalid. Future work requires EV-aware thresholds, percentile thresholds, dynamic decision boundaries, calibration-aware walk-forward integration - not literal-probability thresholds.</span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a><span class="fu">## Priority 2 - Regime Segmentation</span></span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a>Objective: determine where the edge exists, where it disappears, when the strategy should deactivate.</span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a>Files: regime_segmentation.py, regime_volatility.csv, trend_regime_segmentation.py, trend_regime_report.csv, dma200_report.csv, regime_analysis.py, regime_report.csv.</span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a>Volatility regimes:</span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a>| Regime | Winrate | Avg Return |</span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a>|---|---|---|</span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a>| Q4_HIGH | 64.15% | 1.24% |</span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a>| Q3_MEDHIGH | 67.03% | 0.87% |</span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a>| Q2_MEDLOW | 63.55% | 0.59% |</span>
<span id="cb1-79"><a href="#cb1-79" aria-hidden="true" tabindex="-1"></a>| Q1_LOW | 64.45% | 0.36% |</span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a>Trend regimes:</span>
<span id="cb1-82"><a href="#cb1-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-83"><a href="#cb1-83" aria-hidden="true" tabindex="-1"></a>| Regime | Winrate | Avg Return |</span>
<span id="cb1-84"><a href="#cb1-84" aria-hidden="true" tabindex="-1"></a>|---|---|---|</span>
<span id="cb1-85"><a href="#cb1-85" aria-hidden="true" tabindex="-1"></a>| BULL_TREND | 67.38% | 0.85% |</span>
<span id="cb1-86"><a href="#cb1-86" aria-hidden="true" tabindex="-1"></a>| BEAR_TREND | 64.08% | 0.74% |</span>
<span id="cb1-87"><a href="#cb1-87" aria-hidden="true" tabindex="-1"></a>| BULL_WEAK | 64.90% | 0.72% |</span>
<span id="cb1-88"><a href="#cb1-88" aria-hidden="true" tabindex="-1"></a>| BEAR_RALLY | 56.77% | 0.56% |</span>
<span id="cb1-89"><a href="#cb1-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-90"><a href="#cb1-90" aria-hidden="true" tabindex="-1"></a>200 DMA regimes:</span>
<span id="cb1-91"><a href="#cb1-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-92"><a href="#cb1-92" aria-hidden="true" tabindex="-1"></a>| Regime | Winrate |</span>
<span id="cb1-93"><a href="#cb1-93" aria-hidden="true" tabindex="-1"></a>|---|---|</span>
<span id="cb1-94"><a href="#cb1-94" aria-hidden="true" tabindex="-1"></a>| ABOVE_200DMA | 66.89% |</span>
<span id="cb1-95"><a href="#cb1-95" aria-hidden="true" tabindex="-1"></a>| BELOW_200DMA | 62.52% |</span>
<span id="cb1-96"><a href="#cb1-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-97"><a href="#cb1-97" aria-hidden="true" tabindex="-1"></a>Interpretation: the system is not always-on alpha. It behaves as conditional regime alpha: best in bullish trend + above 200DMA + high volatility; worst in bear rallies. This motivated the meta-regime filtering research in Chapter 3.</span>
<span id="cb1-98"><a href="#cb1-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-99"><a href="#cb1-99" aria-hidden="true" tabindex="-1"></a><span class="fu">## Priority 3 - Reality Modeling (Friction Stress Test)</span></span>
<span id="cb1-100"><a href="#cb1-100" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-101"><a href="#cb1-101" aria-hidden="true" tabindex="-1"></a>Objective: stress-test the system under realistic trading conditions: spread widening, slippage expansion, liquidity degradation, execution friction.</span>
<span id="cb1-102"><a href="#cb1-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-103"><a href="#cb1-103" aria-hidden="true" tabindex="-1"></a>Files: reality_modeling.py, reality_modeling_report.csv.</span>
<span id="cb1-104"><a href="#cb1-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-105"><a href="#cb1-105" aria-hidden="true" tabindex="-1"></a>| Scenario | Outcome |</span>
<span id="cb1-106"><a href="#cb1-106" aria-hidden="true" tabindex="-1"></a>|---|---|</span>
<span id="cb1-107"><a href="#cb1-107" aria-hidden="true" tabindex="-1"></a>| BASELINE | Extremely profitable |</span>
<span id="cb1-108"><a href="#cb1-108" aria-hidden="true" tabindex="-1"></a>| LIGHT_FRICTION | Survived |</span>
<span id="cb1-109"><a href="#cb1-109" aria-hidden="true" tabindex="-1"></a>| MEDIUM_FRICTION | Survived |</span>
<span id="cb1-110"><a href="#cb1-110" aria-hidden="true" tabindex="-1"></a>| HEAVY_FRICTION | Survived |</span>
<span id="cb1-111"><a href="#cb1-111" aria-hidden="true" tabindex="-1"></a>| EXTREME_FRICTION | Collapsed |</span>
<span id="cb1-112"><a href="#cb1-112" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-113"><a href="#cb1-113" aria-hidden="true" tabindex="-1"></a>Interpretation: the edge survives realistic execution friction and moderate liquidity degradation, but catastrophic friction destroys profitability. Execution quality remains critical.</span>
<span id="cb1-114"><a href="#cb1-114" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-115"><a href="#cb1-115" aria-hidden="true" tabindex="-1"></a><span class="fu">## Priority 4 - Position Sizing Research</span></span>
<span id="cb1-116"><a href="#cb1-116" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-117"><a href="#cb1-117" aria-hidden="true" tabindex="-1"></a>Objective: determine optimal leverage, Kelly sizing, volatility targeting feasibility.</span>
<span id="cb1-118"><a href="#cb1-118" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-119"><a href="#cb1-119" aria-hidden="true" tabindex="-1"></a>Files: fractional_kelly_research.py, fractional_kelly_report.csv, vol_targeting_report.csv.</span>
<span id="cb1-120"><a href="#cb1-120" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-121"><a href="#cb1-121" aria-hidden="true" tabindex="-1"></a>Full Kelly estimate: 0.505 - unusually high for a systematic trading system.</span>
<span id="cb1-122"><a href="#cb1-122" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-123"><a href="#cb1-123" aria-hidden="true" tabindex="-1"></a>| Fraction | Max DD |</span>
<span id="cb1-124"><a href="#cb1-124" aria-hidden="true" tabindex="-1"></a>|---|---|</span>
<span id="cb1-125"><a href="#cb1-125" aria-hidden="true" tabindex="-1"></a>| 0.10 Kelly | -0.78% |</span>
<span id="cb1-126"><a href="#cb1-126" aria-hidden="true" tabindex="-1"></a>| 0.25 Kelly | -1.94% |</span>
<span id="cb1-127"><a href="#cb1-127" aria-hidden="true" tabindex="-1"></a>| 0.50 Kelly | -3.84% |</span>
<span id="cb1-128"><a href="#cb1-128" aria-hidden="true" tabindex="-1"></a>| 0.75 Kelly | -5.71% |</span>
<span id="cb1-129"><a href="#cb1-129" aria-hidden="true" tabindex="-1"></a>| 1.00 Kelly | -7.54% |</span>
<span id="cb1-130"><a href="#cb1-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-131"><a href="#cb1-131" aria-hidden="true" tabindex="-1"></a>Interpretation: the system appears risk-scalable and leverage-tolerant, with Sharpe remaining approximately constant across leverage scaling (near-linear behavior under scaling) - atypical for overfit systems. Full Kelly introduces unnecessary volatility; fractional Kelly dramatically improves survivability.</span>
<span id="cb1-132"><a href="#cb1-132" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-133"><a href="#cb1-133" aria-hidden="true" tabindex="-1"></a><span class="fu">## Priority 5 - Randomized Label Sanity Check</span></span>
<span id="cb1-134"><a href="#cb1-134" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-135"><a href="#cb1-135" aria-hidden="true" tabindex="-1"></a>Objective: determine whether the model extracts genuine signal or exploits noise.</span>
<span id="cb1-136"><a href="#cb1-136" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-137"><a href="#cb1-137" aria-hidden="true" tabindex="-1"></a>Files: randomized_labels_sanity.py, randomized_labels_report.csv.</span>
<span id="cb1-138"><a href="#cb1-138" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-139"><a href="#cb1-139" aria-hidden="true" tabindex="-1"></a>| Metric | Value |</span>
<span id="cb1-140"><a href="#cb1-140" aria-hidden="true" tabindex="-1"></a>|---|---|</span>
<span id="cb1-141"><a href="#cb1-141" aria-hidden="true" tabindex="-1"></a>| Mean Accuracy | 72.9% |</span>
<span id="cb1-142"><a href="#cb1-142" aria-hidden="true" tabindex="-1"></a>| Mean Precision | 0.044 |</span>
<span id="cb1-143"><a href="#cb1-143" aria-hidden="true" tabindex="-1"></a>| Mean Recall | 0.009 |</span>
<span id="cb1-144"><a href="#cb1-144" aria-hidden="true" tabindex="-1"></a>| Mean F1 | 0.014 |</span>
<span id="cb1-145"><a href="#cb1-145" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-146"><a href="#cb1-146" aria-hidden="true" tabindex="-1"></a>Interpretation: when labels were randomized, predictive quality collapsed (F1 near-vanished, recall disappeared). Strong evidence the original model is not simply memorizing noise. High accuracy under randomization is a base-rate artifact (class imbalance), not a signal - F1/recall are the diagnostic metrics here.</span>
<span id="cb1-147"><a href="#cb1-147" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-148"><a href="#cb1-148" aria-hidden="true" tabindex="-1"></a><span class="fu">## Priority 6 - Trade Dependency Analysis</span></span>
<span id="cb1-149"><a href="#cb1-149" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-150"><a href="#cb1-150" aria-hidden="true" tabindex="-1"></a>Objective: study clustering, path dependency, serial correlation, streak behavior.</span>
<span id="cb1-151"><a href="#cb1-151" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-152"><a href="#cb1-152" aria-hidden="true" tabindex="-1"></a>Files: trade_dependency_analysis.py, trade_dependency_report.csv.</span>
<span id="cb1-153"><a href="#cb1-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-154"><a href="#cb1-154" aria-hidden="true" tabindex="-1"></a>| Metric | Value |</span>
<span id="cb1-155"><a href="#cb1-155" aria-hidden="true" tabindex="-1"></a>|---|---|</span>
<span id="cb1-156"><a href="#cb1-156" aria-hidden="true" tabindex="-1"></a>| Global Winrate | 64.79% |</span>
<span id="cb1-157"><a href="#cb1-157" aria-hidden="true" tabindex="-1"></a>| Avg Win Streak | 17.94 |</span>
<span id="cb1-158"><a href="#cb1-158" aria-hidden="true" tabindex="-1"></a>| Max Win Streak | 120 |</span>
<span id="cb1-159"><a href="#cb1-159" aria-hidden="true" tabindex="-1"></a>| Avg Loss Streak | 9.75 |</span>
<span id="cb1-160"><a href="#cb1-160" aria-hidden="true" tabindex="-1"></a>| Max Loss Streak | 52 |</span>
<span id="cb1-161"><a href="#cb1-161" aria-hidden="true" tabindex="-1"></a>| Lag-1 Autocorrelation | 0.851 |</span>
<span id="cb1-162"><a href="#cb1-162" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-163"><a href="#cb1-163" aria-hidden="true" tabindex="-1"></a>Interpretation: trades exhibit significant clustering, non-random sequencing, and persistent market-state behavior - further support for regime dependence and structural conditional alpha (rather than i.i.d. edge).</span>
<span id="cb1-164"><a href="#cb1-164" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-165"><a href="#cb1-165" aria-hidden="true" tabindex="-1"></a><span class="fu">## Priority 7 - White's Reality Check / SPA</span></span>
<span id="cb1-166"><a href="#cb1-166" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-167"><a href="#cb1-167" aria-hidden="true" tabindex="-1"></a>Objective: test whether the observed edge survives multiple-testing bias and data-snooping concerns.</span>
<span id="cb1-168"><a href="#cb1-168" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-169"><a href="#cb1-169" aria-hidden="true" tabindex="-1"></a>Files: whites_reality_check.py, whites_reality_check_report.csv.</span>
<span id="cb1-170"><a href="#cb1-170" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-171"><a href="#cb1-171" aria-hidden="true" tabindex="-1"></a>| Metric | Value |</span>
<span id="cb1-172"><a href="#cb1-172" aria-hidden="true" tabindex="-1"></a>|---|---|</span>
<span id="cb1-173"><a href="#cb1-173" aria-hidden="true" tabindex="-1"></a>| Observed Mean Return | 0.007652 |</span>
<span id="cb1-174"><a href="#cb1-174" aria-hidden="true" tabindex="-1"></a>| Std Return | 0.011966 |</span>
<span id="cb1-175"><a href="#cb1-175" aria-hidden="true" tabindex="-1"></a>| Sharpe-like | 0.6395 |</span>
<span id="cb1-176"><a href="#cb1-176" aria-hidden="true" tabindex="-1"></a>| White RC p-value | 0.506 (FAIL) |</span>
<span id="cb1-177"><a href="#cb1-177" aria-hidden="true" tabindex="-1"></a>| SPA Sign-Flip p-value | 0.000 (PASS) |</span>
<span id="cb1-178"><a href="#cb1-178" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-179"><a href="#cb1-179" aria-hidden="true" tabindex="-1"></a>Interpretation - mixed result. White's Reality Check fails (p=0.506), suggesting possible sensitivity to data-mining bias when benchmarked against a large universe of alternatives. The SPA sign-flip approximation passes (p=0.000). This is not definitive proof of edge, but also not a rejection. See Chapter 3 for the regime-conditional SPA re-analysis (BEAR/LATERAL/BULL, all p=0.000 vs buy-and-hold), which explains the global White RC failure as a benchmark-selection artifact (buy-and-hold in BTC's strongest historical bull run), not model data-snooping.</span>
<span id="cb1-180"><a href="#cb1-180" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-181"><a href="#cb1-181" aria-hidden="true" tabindex="-1"></a><span class="fu">## Feature Significance / Stability</span></span>
<span id="cb1-182"><a href="#cb1-182" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-183"><a href="#cb1-183" aria-hidden="true" tabindex="-1"></a>Objective: measure feature importance, stability, overfit indicators.</span>
<span id="cb1-184"><a href="#cb1-184" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-185"><a href="#cb1-185" aria-hidden="true" tabindex="-1"></a>Files: feature_significance.py, feature_significance_full.csv, feature_significance_summary.csv.</span>
<span id="cb1-186"><a href="#cb1-186" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-187"><a href="#cb1-187" aria-hidden="true" tabindex="-1"></a>Initial finding (XGBoost gain/cover importance): most features displayed unstable importance - volume, MACD derivatives, EMA structures, RSI, ATR all highly unstable. Interpretation: edge may emerge from feature interaction, not single dominant predictors; possible regime dependence; possible need for adaptive models.</span>
<span id="cb1-188"><a href="#cb1-188" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-189"><a href="#cb1-189" aria-hidden="true" tabindex="-1"></a>Superseding finding (SHAP stability, later session - see Chapter 4): using SHAP instead of XGBoost gain/cover (methodologically superior - SHAP measures actual contribution to output), all features show CV &lt; 0.5 (stability threshold):</span>
<span id="cb1-190"><a href="#cb1-190" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-191"><a href="#cb1-191" aria-hidden="true" tabindex="-1"></a>| Feature | CV | Status |</span>
<span id="cb1-192"><a href="#cb1-192" aria-hidden="true" tabindex="-1"></a>|---|---|---|</span>
<span id="cb1-193"><a href="#cb1-193" aria-hidden="true" tabindex="-1"></a>| macd_diff | 0.169 | STABLE |</span>
<span id="cb1-194"><a href="#cb1-194" aria-hidden="true" tabindex="-1"></a>| rsi_14 | 0.272 | STABLE |</span>
<span id="cb1-195"><a href="#cb1-195" aria-hidden="true" tabindex="-1"></a>| atr | 0.275 | STABLE |</span>
<span id="cb1-196"><a href="#cb1-196" aria-hidden="true" tabindex="-1"></a>| macd | 0.352 | STABLE |</span>
<span id="cb1-197"><a href="#cb1-197" aria-hidden="true" tabindex="-1"></a>| macd_signal | 0.359 | STABLE |</span>
<span id="cb1-198"><a href="#cb1-198" aria-hidden="true" tabindex="-1"></a>| ema_10 | 0.373 | STABLE |</span>
<span id="cb1-199"><a href="#cb1-199" aria-hidden="true" tabindex="-1"></a>| ema_30 | 0.419 | STABLE |</span>
<span id="cb1-200"><a href="#cb1-200" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-201"><a href="#cb1-201" aria-hidden="true" tabindex="-1"></a>Ranking by average importance: ema_30 (0.0947, structural anchor) &gt; atr (0.0334) &gt; macd (0.0279) &gt; ema_10 (0.0229) &gt; macd_diff (0.0177) &gt; rsi_14 (0.0126) &gt; macd_signal (0.0084). Notable event: ema_30 importance drops from 0.1005 to 0.0224 in Nov 2024 (post-election ATH breakout), with rsi_14 compensating - interpreted as healthy model adaptation, not fragility.</span>
<span id="cb1-202"><a href="#cb1-202" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-203"><a href="#cb1-203" aria-hidden="true" tabindex="-1"></a>Note: the original (unstable) finding used XGBoost gain/cover; the later SHAP analysis supersedes it methodologically. Both are kept here since they come from different research sessions and use different feature sets - flagged for reconciliation in the Appendix.</span>
<span id="cb1-204"><a href="#cb1-204" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-205"><a href="#cb1-205" aria-hidden="true" tabindex="-1"></a><span class="fu">## Monte Carlo Analysis</span></span>
<span id="cb1-206"><a href="#cb1-206" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-207"><a href="#cb1-207" aria-hidden="true" tabindex="-1"></a>Objective: stress-test return distribution robustness: path variability, probabilistic survivability, drawdown robustness, compounding stability.</span>
<span id="cb1-208"><a href="#cb1-208" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-209"><a href="#cb1-209" aria-hidden="true" tabindex="-1"></a>Files: montecarlo.py, montecarlo_results.csv, montecarlo_distribution.png, montecarlo_equity_curves.png.</span>
<span id="cb1-210"><a href="#cb1-210" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-211"><a href="#cb1-211" aria-hidden="true" tabindex="-1"></a>Three methods run: reshuffle, bootstrap, block bootstrap. Sample of results (final equity from $1,000 start, 4 runs shown):</span>
<span id="cb1-212"><a href="#cb1-212" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-213"><a href="#cb1-213" aria-hidden="true" tabindex="-1"></a>| Method | Sample Final Equity Range |</span>
<span id="cb1-214"><a href="#cb1-214" aria-hidden="true" tabindex="-1"></a>|---|---|</span>
<span id="cb1-215"><a href="#cb1-215" aria-hidden="true" tabindex="-1"></a>| Reshuffle | ~$63,826 (constant across runs - deterministic reshuffle of fixed trade set) |</span>
<span id="cb1-216"><a href="#cb1-216" aria-hidden="true" tabindex="-1"></a>| Bootstrap | $56,253 - $65,236 |</span>
<span id="cb1-217"><a href="#cb1-217" aria-hidden="true" tabindex="-1"></a>| Block Bootstrap | $50,050 - $92,153 |</span>
<span id="cb1-218"><a href="#cb1-218" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-219"><a href="#cb1-219" aria-hidden="true" tabindex="-1"></a><span class="al">![Monte Carlo distribution: reshuffle, bootstrap, and block-bootstrap final equity distributions.](images/montecarlo_distribution.png)</span>{#fig-mc-dist width=90%}</span>
<span id="cb1-220"><a href="#cb1-220" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-221"><a href="#cb1-221" aria-hidden="true" tabindex="-1"></a><span class="al">![Monte Carlo equity curves: simulated paths under reshuffle, bootstrap, and block-bootstrap methods.](images/montecarlo_equity_curves.png)</span>{#fig-mc-equity width=90%}</span>
<span id="cb1-222"><a href="#cb1-222" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-223"><a href="#cb1-223" aria-hidden="true" tabindex="-1"></a>Note: these figures are approximately 8x larger than the walk-forward baseline equity ($7,989-$8,590 depending on source). This suggests the Monte Carlo in statistics/ may be running over a different (possibly longer or unfiltered) trade set than the walk-forward baseline - flagged in the Appendix for reconciliation, not yet explained.</span>
<span id="cb1-224"><a href="#cb1-224" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-225"><a href="#cb1-225" aria-hidden="true" tabindex="-1"></a><span class="fu">## Final Conclusions (per statistics/README.md)</span></span>
<span id="cb1-226"><a href="#cb1-226" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-227"><a href="#cb1-227" aria-hidden="true" tabindex="-1"></a>The audit strongly suggests the system likely possesses genuine conditional edge:</span>
<span id="cb1-228"><a href="#cb1-228" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-229"><a href="#cb1-229" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>survives randomized labels,</span>
<span id="cb1-230"><a href="#cb1-230" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>survives realistic friction,</span>
<span id="cb1-231"><a href="#cb1-231" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>improves coherently under favorable regimes,</span>
<span id="cb1-232"><a href="#cb1-232" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>displays structured clustering,</span>
<span id="cb1-233"><a href="#cb1-233" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>remains profitable under leverage scaling.</span>
<span id="cb1-234"><a href="#cb1-234" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-235"><a href="#cb1-235" aria-hidden="true" tabindex="-1"></a>However, the system is not yet production-grade. Remaining critical tasks: live shadow deployment, calibration-aware walk-forward, dynamic thresholds, funding/perp features, microstructure signals, order-flow integration, live execution validation (see Chapter 6 - Roadmap).</span>
<span id="cb1-236"><a href="#cb1-236" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-237"><a href="#cb1-237" aria-hidden="true" tabindex="-1"></a>Current classification: "Research-grade promising systematic strategy" - not yet institutional production system, but substantially beyond hobby backtesting.</span></code><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/erictvillarreal/RoboTrader812/edit/main/02-statistical-due-diligence.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/erictvillarreal/RoboTrader812/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer><script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>