<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.39">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>4&nbsp; Live Validation – S4BTC</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./05-deployment.html" rel="next">
<link href="./03-regime-research.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-0626ff4d7a71b55c8707dcae1d04a9b6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-0f1d7832f862a9a05de4b1f937104ab7.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


</head>

<body class="nav-sidebar floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">S4BTC</span>
    </a>
  </div>
        <div class="quarto-navbar-tools tools-end">
    <a href="https://github.com/erictvillarreal/RoboTrader812" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
          <div id="quarto-search" class="" title="Search"></div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./04-live-validation.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Live Validation</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Executive Summary</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-architecture.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">System Architecture</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-statistical-due-diligence.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Statistical Due Diligence</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-regime-research.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Regime Research</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-live-validation.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Live Validation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-deployment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Deployment</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-roadmap.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Roadmap — Open Gaps &amp; Next Steps</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./99-appendix-data-sources.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Appendix — Data Source Reconciliation</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#context" id="toc-context" class="nav-link active" data-scroll-target="#context"><span class="header-section-number">4.1</span> Context</a></li>
  <li><a href="#production-bugs-fixed-on-main" id="toc-production-bugs-fixed-on-main" class="nav-link" data-scroll-target="#production-bugs-fixed-on-main"><span class="header-section-number">4.2</span> Production Bugs Fixed (on main)</a>
  <ul class="collapse">
  <li><a href="#bug-1-ev_gap_perc-6000x-scale-error" id="toc-bug-1-ev_gap_perc-6000x-scale-error" class="nav-link" data-scroll-target="#bug-1-ev_gap_perc-6000x-scale-error"><span class="header-section-number">4.2.1</span> Bug 1 — ev_gap_perc: 6,000x scale error</a></li>
  <li><a href="#bug-2-leverage-nameerror" id="toc-bug-2-leverage-nameerror" class="nav-link" data-scroll-target="#bug-2-leverage-nameerror"><span class="header-section-number">4.2.2</span> Bug 2 — LEVERAGE NameError</a></li>
  <li><a href="#bug-3-malformed-f-string-in-send_trade_closed" id="toc-bug-3-malformed-f-string-in-send_trade_closed" class="nav-link" data-scroll-target="#bug-3-malformed-f-string-in-send_trade_closed"><span class="header-section-number">4.2.3</span> Bug 3 — Malformed f-string in send_trade_closed</a></li>
  <li><a href="#feature-added-daily-telegram-ledger-dump" id="toc-feature-added-daily-telegram-ledger-dump" class="nav-link" data-scroll-target="#feature-added-daily-telegram-ledger-dump"><span class="header-section-number">4.2.4</span> Feature Added — Daily Telegram Ledger Dump</a></li>
  <li><a href="#candle-synchronization-bug-live-runtime-stability-patch-may-2026" id="toc-candle-synchronization-bug-live-runtime-stability-patch-may-2026" class="nav-link" data-scroll-target="#candle-synchronization-bug-live-runtime-stability-patch-may-2026"><span class="header-section-number">4.2.5</span> Candle Synchronization Bug (Live Runtime Stability Patch, May 2026)</a></li>
  </ul></li>
  <li><a href="#statistical-gaps-status" id="toc-statistical-gaps-status" class="nav-link" data-scroll-target="#statistical-gaps-status"><span class="header-section-number">4.3</span> Statistical Gaps — Status</a>
  <ul class="collapse">
  <li><a href="#gap-2-kelly-sizing-miscalibration---closed" id="toc-gap-2-kelly-sizing-miscalibration---closed" class="nav-link" data-scroll-target="#gap-2-kelly-sizing-miscalibration---closed"><span class="header-section-number">4.3.1</span> Gap 2 — Kelly sizing miscalibration -&gt; CLOSED</a></li>
  <li><a href="#gap-3-spa-bootstrap-complete---closed" id="toc-gap-3-spa-bootstrap-complete---closed" class="nav-link" data-scroll-target="#gap-3-spa-bootstrap-complete---closed"><span class="header-section-number">4.3.2</span> Gap 3 — SPA Bootstrap complete -&gt; CLOSED</a></li>
  <li><a href="#gap-4-unstable-features---closed" id="toc-gap-4-unstable-features---closed" class="nav-link" data-scroll-target="#gap-4-unstable-features---closed"><span class="header-section-number">4.3.3</span> Gap 4 — Unstable features -&gt; CLOSED</a></li>
  <li><a href="#gap-5-no-microstructure-features---in-progress" id="toc-gap-5-no-microstructure-features---in-progress" class="nav-link" data-scroll-target="#gap-5-no-microstructure-features---in-progress"><span class="header-section-number">4.3.4</span> Gap 5 — No microstructure features -&gt; IN PROGRESS</a></li>
  </ul></li>
  <li><a href="#the-30-day-live-paper-trading-result-and-root-cause" id="toc-the-30-day-live-paper-trading-result-and-root-cause" class="nav-link" data-scroll-target="#the-30-day-live-paper-trading-result-and-root-cause"><span class="header-section-number">4.4</span> The 30-Day Live Paper Trading Result and Root Cause</a>
  <ul class="collapse">
  <li><a href="#the-real-result" id="toc-the-real-result" class="nav-link" data-scroll-target="#the-real-result"><span class="header-section-number">4.4.1</span> The Real Result</a></li>
  <li><a href="#hypothesis-tested-and-rejected-low-volatility" id="toc-hypothesis-tested-and-rejected-low-volatility" class="nav-link" data-scroll-target="#hypothesis-tested-and-rejected-low-volatility"><span class="header-section-number">4.4.2</span> Hypothesis Tested and Rejected: Low Volatility</a></li>
  <li><a href="#additional-finding-directional-efficiency-not-candle-volatility" id="toc-additional-finding-directional-efficiency-not-candle-volatility" class="nav-link" data-scroll-target="#additional-finding-directional-efficiency-not-candle-volatility"><span class="header-section-number">4.4.3</span> Additional Finding: Directional Efficiency, Not Candle Volatility</a></li>
  </ul></li>
  <li><a href="#retrain-validation-final-result-26-jun-2026" id="toc-retrain-validation-final-result-26-jun-2026" class="nav-link" data-scroll-target="#retrain-validation-final-result-26-jun-2026"><span class="header-section-number">4.5</span> Retrain Validation — Final Result (26 Jun 2026)</a>
  <ul class="collapse">
  <li><a href="#retroactive-out-of-sample-validation-on-the-real-30-day-period" id="toc-retroactive-out-of-sample-validation-on-the-real-30-day-period" class="nav-link" data-scroll-target="#retroactive-out-of-sample-validation-on-the-real-30-day-period"><span class="header-section-number">4.5.1</span> Retroactive Out-of-Sample Validation on the Real 30-Day Period</a></li>
  </ul></li>
  <li><a href="#live-paper-trading-day-0-onwards-27-jun-2026" id="toc-live-paper-trading-day-0-onwards-27-jun-2026" class="nav-link" data-scroll-target="#live-paper-trading-day-0-onwards-27-jun-2026"><span class="header-section-number">4.6</span> Live Paper Trading — Day 0 Onwards (27 Jun 2026)</a>
  <ul class="collapse">
  <li><a href="#second-retrain-25-jul-2026" id="toc-second-retrain-25-jul-2026" class="nav-link" data-scroll-target="#second-retrain-25-jul-2026"><span class="header-section-number">4.6.1</span> Second Retrain — 25 Jul 2026</a></li>
  <li><a href="#live-trade-ledger-27-jun-10-jul-2026" id="toc-live-trade-ledger-27-jun-10-jul-2026" class="nav-link" data-scroll-target="#live-trade-ledger-27-jun-10-jul-2026"><span class="header-section-number">4.6.2</span> Live Trade Ledger (27 Jun – 10 Jul 2026)</a></li>
  <li><a href="#simulated-performance-oct-2024-jul-2026" id="toc-simulated-performance-oct-2024-jul-2026" class="nav-link" data-scroll-target="#simulated-performance-oct-2024-jul-2026"><span class="header-section-number">4.6.3</span> Simulated Performance Oct 2024 – Jul 2026</a></li>
  </ul></li>
  <li><a href="#rd-findings-economic-thesis-jul-2026" id="toc-rd-findings-economic-thesis-jul-2026" class="nav-link" data-scroll-target="#rd-findings-economic-thesis-jul-2026"><span class="header-section-number">4.7</span> R&amp;D Findings — Economic Thesis (Jul 2026)</a>
  <ul class="collapse">
  <li><a href="#h1-serial-autocorrelation-rejected" id="toc-h1-serial-autocorrelation-rejected" class="nav-link" data-scroll-target="#h1-serial-autocorrelation-rejected"><span class="header-section-number">4.7.1</span> H1: Serial Autocorrelation (Rejected)</a></li>
  <li><a href="#h2-session-dependent-win-rate" id="toc-h2-session-dependent-win-rate" class="nav-link" data-scroll-target="#h2-session-dependent-win-rate"><span class="header-section-number">4.7.2</span> H2: Session-Dependent Win Rate</a></li>
  <li><a href="#pnl-attribution" id="toc-pnl-attribution" class="nav-link" data-scroll-target="#pnl-attribution"><span class="header-section-number">4.7.3</span> PnL Attribution</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/erictvillarreal/RoboTrader812/edit/main/04-live-validation.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/erictvillarreal/RoboTrader812/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Live Validation</span></h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="context" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="context"><span class="header-section-number">4.1</span> Context</h2>
<p>Diagnostic and mitigation session for statistical gaps identified in a prior institutional audit. The bot had been deployed on Railway for ~20 days with minimal activity (4 trades in 10 stable days). Source: CLAUDE_README_RESEARCH_SESSION_MAY25.md, author Eric Trevino, branch research/recalibration-meta-regime.</p>
</section>
<section id="production-bugs-fixed-on-main" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="production-bugs-fixed-on-main"><span class="header-section-number">4.2</span> Production Bugs Fixed (on main)</h2>
<section id="bug-1-ev_gap_perc-6000x-scale-error" class="level3" data-number="4.2.1">
<h3 data-number="4.2.1" class="anchored" data-anchor-id="bug-1-ev_gap_perc-6000x-scale-error"><span class="header-section-number">4.2.1</span> Bug 1 — ev_gap_perc: 6,000x scale error</h3>
<p>File: s4_deploy/s4_policy.py.</p>
<p>Problem: compared EV in dollars against the cost of a full BTC unit. Previous threshold approximately $185; correct threshold approximately $0.03. A trade with EV=$83 was being rejected because it did not reach $185.</p>
<pre><code># Before (bug)
cost_only = (COMMISSION + SLIPPAGE) * close * 2
if ev &lt; cost_only * (1 + EV_GAP_PERC):

# After (correct - replicates walk.py line 416)
stake0 = equity * POSITION_FRAC
if ev &lt; stake0 * EV_GAP_PERC:</code></pre>
<p>Impact: the bot rejected approximately 100% of valid trades for 20 days. First candle post-fix: take=True dir=short ev=83.17 reason=ok.</p>
</section>
<section id="bug-2-leverage-nameerror" class="level3" data-number="4.2.2">
<h3 data-number="4.2.2" class="anchored" data-anchor-id="bug-2-leverage-nameerror"><span class="header-section-number">4.2.2</span> Bug 2 — LEVERAGE NameError</h3>
<p>File: s4_deploy/trader.py. LEVERAGE was used in notional = d.stake * LEVERAGE but not imported from config.py. Fix: added to the import block.</p>
</section>
<section id="bug-3-malformed-f-string-in-send_trade_closed" class="level3" data-number="4.2.3">
<h3 data-number="4.2.3" class="anchored" data-anchor-id="bug-3-malformed-f-string-in-send_trade_closed"><span class="header-section-number">4.2.3</span> Bug 3 — Malformed f-string in send_trade_closed</h3>
<p>File: s4_deploy/telegram_notifier.py.</p>
<pre><code># Before (bug)
f"(${tp:,.2f if outcome == 'tp' else sl:,.2f})"

# After
f"(${(tp if win else sl):,.2f})"</code></pre>
</section>
<section id="feature-added-daily-telegram-ledger-dump" class="level3" data-number="4.2.4">
<h3 data-number="4.2.4" class="anchored" data-anchor-id="feature-added-daily-telegram-ledger-dump"><span class="header-section-number">4.2.4</span> Feature Added — Daily Telegram Ledger Dump</h3>
<p>Files: s4_deploy/telegram_notifier.py, s4_deploy/trader.py. At 00:00 UTC daily, the bot sends the full ledger CSV via Telegram (protocol: copy-paste into Google Sheets). Implemented as a data-recovery mechanism during the ephemeral storage period; superseded by the Railway Volume configured on 27 Jun 2026 (<code>/app/persist</code>), but retained as an independent audit trail.</p>
</section>
<section id="candle-synchronization-bug-live-runtime-stability-patch-may-2026" class="level3" data-number="4.2.5">
<h3 data-number="4.2.5" class="anchored" data-anchor-id="candle-synchronization-bug-live-runtime-stability-patch-may-2026"><span class="header-section-number">4.2.5</span> Candle Synchronization Bug (Live Runtime Stability Patch, May 2026)</h3>
<p>Symptom: the model repeated the exact same p_up across multiple consecutive candles — not caused by the XGBoost model or feature engineering.</p>
<p>Root cause: the main loop was querying Binance too close to the candle close boundary (approximately 2 seconds after UTC boundary), causing the API to return a still-partially-synced previous candle. Consequence: the bot reused the same closed candle multiple times, p_up appeared “stuck,” the system rejected trades via prob_edge_low, and statistical sampling was partially contaminated.</p>
<p>Fix: candle close buffer adjustment in the polling loop timing (implementation detail in trader.py).</p>
</section>
</section>
<section id="statistical-gaps-status" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="statistical-gaps-status"><span class="header-section-number">4.3</span> Statistical Gaps — Status</h2>
<section id="gap-2-kelly-sizing-miscalibration---closed" class="level3" data-number="4.3.1">
<h3 data-number="4.3.1" class="anchored" data-anchor-id="gap-2-kelly-sizing-miscalibration---closed"><span class="header-section-number">4.3.1</span> Gap 2 — Kelly sizing miscalibration -&gt; CLOSED</h3>
<p>The ev_gap_perc bug (Bug 1 above) was the production manifestation of this gap. With the fix, sizing now operates exactly as in backtest.</p>
</section>
<section id="gap-3-spa-bootstrap-complete---closed" class="level3" data-number="4.3.2">
<h3 data-number="4.3.2" class="anchored" data-anchor-id="gap-3-spa-bootstrap-complete---closed"><span class="header-section-number">4.3.2</span> Gap 3 — SPA Bootstrap complete -&gt; CLOSED</h3>
<p>File: statistics/spa_bootstrap_results.csv. SPA bootstrap (Hansen 2005) with stationary bootstrap (Politis and Romano, block_size=24h) against 500 benchmarks (250 random-threshold strategies, 125 permuted-feature strategies, 125 scaled buy-and-hold).</p>
<p>Global result: SPA p=0.478 — fails for a structural reason (BTC rose 5x during 2022-2026, favoring buy-and-hold in this benchmark universe).</p>
<p>SPA by regime (key finding) — S4 beats buy-and-hold in all three regimes, p=0.000:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Regime</th>
<th>Trades</th>
<th>Return S4</th>
<th>Return B&amp;H</th>
<th>Ratio</th>
<th>p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>BEAR</td>
<td>3,202</td>
<td>0.004826</td>
<td>0.000910</td>
<td>5.3x</td>
<td>0.0000</td>
</tr>
<tr class="even">
<td>LATERAL</td>
<td>3,169</td>
<td>0.003741</td>
<td>0.000761</td>
<td>4.9x</td>
<td>0.0000</td>
</tr>
<tr class="odd">
<td>BULL</td>
<td>9,571</td>
<td>0.004864</td>
<td>0.000887</td>
<td>5.5x</td>
<td>0.0000</td>
</tr>
</tbody>
</table>
<p>Interpretation: the global SPA failure was a benchmark artifact (buy-and-hold during BTC’s strongest historical bull run), not model data-snooping.</p>
</section>
<section id="gap-4-unstable-features---closed" class="level3" data-number="4.3.3">
<h3 data-number="4.3.3" class="anchored" data-anchor-id="gap-4-unstable-features---closed"><span class="header-section-number">4.3.3</span> Gap 4 — Unstable features -&gt; CLOSED</h3>
<p>See Chapter 2 (Feature Significance) for the SHAP stability analysis that superseded the earlier XGBoost gain/cover finding.</p>
</section>
<section id="gap-5-no-microstructure-features---in-progress" class="level3" data-number="4.3.4">
<h3 data-number="4.3.4" class="anchored" data-anchor-id="gap-5-no-microstructure-features---in-progress"><span class="header-section-number">4.3.4</span> Gap 5 — No microstructure features -&gt; IN PROGRESS</h3>
<p>Files: statistics/market_microstructure/open_interest_analysis.py, statistics/market_microstructure/artifacts/microstructure_features.csv.</p>
<p>Fetcher implemented via OKX (Binance and Bybit IP-blocked from Mexico/datacenter). 697 rows generated, 30 days of history. Features: oi_change_1h, oi_change_8h, oi_zscore_24h, volume_oi_ratio, funding_rate (forward-filled), funding_sign, funding_extreme (1 if abs(funding) &gt; 2 historical std).</p>
<p>Pending: integrate into the day-30 model retrain — will require reconstructing the historical dataset with these features back to 2022 via OKX history.</p>
</section>
</section>
<section id="the-30-day-live-paper-trading-result-and-root-cause" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="the-30-day-live-paper-trading-result-and-root-cause"><span class="header-section-number">4.4</span> The 30-Day Live Paper Trading Result and Root Cause</h2>
<section id="the-real-result" class="level3" data-number="4.4.1">
<h3 data-number="4.4.1" class="anchored" data-anchor-id="the-real-result"><span class="header-section-number">4.4.1</span> The Real Result</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Metric</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Period</td>
<td>14 May - 25 Jun 2026</td>
</tr>
<tr class="even">
<td>Return</td>
<td>-0.98% ($1,000 -&gt; $990.24)</td>
</tr>
<tr class="odd">
<td>Winrate</td>
<td>39.66% (vs.&nbsp;74.22% historically expected for this regime)</td>
</tr>
</tbody>
</table>
</section>
<section id="hypothesis-tested-and-rejected-low-volatility" class="level3" data-number="4.4.2">
<h3 data-number="4.4.2" class="anchored" data-anchor-id="hypothesis-tested-and-rejected-low-volatility"><span class="header-section-number">4.4.2</span> Hypothesis Tested and Rejected: Low Volatility</h3>
<p>User hypothesis: the loss was due to low market volatility (a “quiet” regime).</p>
<p>Verified with real data (606 candles, 14 May-25 Jun 2026):</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Volatility category</th>
<th>Frequency</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>HIGH_VOL</td>
<td>244 candles (40.3%) - most frequent</td>
</tr>
<tr class="even">
<td>MIDLOW_VOL</td>
<td>136 candles (22.4%)</td>
</tr>
<tr class="odd">
<td>MIDHIGH_VOL</td>
<td>118 candles (19.5%)</td>
</tr>
<tr class="even">
<td>LOW_VOL</td>
<td>108 candles (17.8%) - least frequent</td>
</tr>
</tbody>
</table>
<p>ATR% average for the period: 0.6461% vs.&nbsp;historical average 0.7406% -&gt; percentile 47.3 (essentially the median). Hypothesis rejected — volatility was normal, and HIGH_VOL was in fact the single most frequent category.</p>
<p>Trend distribution for the period: BEAR_TREND 73.0% (442 candles), BEAR_RALLY 19.3% (117), BULL_TREND 7.8% (47) — a sustained bear market with normal-to-high volatility, not a low-volatility sideways market.</p>
</section>
<section id="additional-finding-directional-efficiency-not-candle-volatility" class="level3" data-number="4.4.3">
<h3 data-number="4.4.3" class="anchored" data-anchor-id="additional-finding-directional-efficiency-not-candle-volatility"><span class="header-section-number">4.4.3</span> Additional Finding: Directional Efficiency, Not Candle Volatility</h3>
<p>After ruling out low candle-level volatility (ATR normal, percentile 47) and ruling out model behavior drift (p_up distribution nearly identical to historical pattern for this regime: mean 0.4531 real vs.&nbsp;0.4411 historical), a third variable was investigated: directional efficiency of movement over multi-hour windows (the system’s real resolution horizon, H=12 candles).</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>Mean 12h return</th>
<th>Std</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Real period (May-Jun 2026)</td>
<td>-0.471%</td>
<td>1.433%</td>
</tr>
<tr class="even">
<td>Historical, same regime (BEAR_TREND + normal vol)</td>
<td>+0.231%</td>
<td>4.968%</td>
</tr>
</tbody>
</table>
<p>The 12-hour return standard deviation during the real period was 3.5x lower than the historical pattern for the same regime (1.433% vs.&nbsp;4.968%), despite 1h ATR looking normal.</p>
<p>Interpretation: 1h ATR measures range within each individual candle but does not capture whether those candles move directionally and cumulatively, or “breathe” back and forth without net progress over longer windows. The period had normal-sized individual candles but high “noise” with low “net advance” over 12h windows — exactly the lethal pattern for a Triple-Barrier system with TP=2xATR: it needs sustained net movement of 2x the entry candle’s ATR, and when the market moves with noise but without sustained directional coherence, SL (which only needs 0.8xATR) triggers disproportionately more than TP — a pattern none of the metrics used in the original diagnosis (1h ATR, trend regime, model behavior) could detect.</p>
<p>Implication for future work: a “directional efficiency” metric (e.g., the ratio of net movement over N candles to the sum of absolute candle-to-candle movements — similar to Kaufman’s Efficiency Ratio) may be a more informative regime feature than single-candle ATR or EMA/DMA trend classification, and is a candidate for future research before permanently ruling out a regime filter based on this dimension.</p>
<p>Final combined root cause: (a) a stale model that never saw this specific period, and (b) low directional efficiency over 12h windows (high noise, low net advance) that no regime metric used prior to this analysis captured. Together these explain the observed 39.66% winrate vs.&nbsp;74.22% historically expected for the same trend/volatility regime.</p>
</section>
</section>
<section id="retrain-validation-final-result-26-jun-2026" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="retrain-validation-final-result-26-jun-2026"><span class="header-section-number">4.5</span> Retrain Validation — Final Result (26 Jun 2026)</h2>
<p>After repairing the dataset (a May data gap was filled) and re-running walk.py in full:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Metric</th>
<th>Retrain</th>
<th>Original Baseline</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Final Equity</td>
<td>$8,465.93</td>
<td>$7,989 (+6%)</td>
</tr>
<tr class="even">
<td>Win rate</td>
<td>64.72%</td>
<td>64.66% (essentially unchanged)</td>
</tr>
<tr class="odd">
<td>CAGR</td>
<td>72.10%</td>
<td>identical to baseline</td>
</tr>
<tr class="even">
<td>Max DD (daily)</td>
<td>-2.04%</td>
<td>identical to baseline</td>
</tr>
<tr class="odd">
<td>Trades</td>
<td>3,050</td>
<td>2,968 (+82, from the extra 2 months)</td>
</tr>
</tbody>
</table>
<p>The retrain replicates historical behavior almost exactly, confirming the architecture, labeling, and model are structurally robust — the problem was never structural.</p>
<section id="retroactive-out-of-sample-validation-on-the-real-30-day-period" class="level3" data-number="4.5.1">
<h3 data-number="4.5.1" class="anchored" data-anchor-id="retroactive-out-of-sample-validation-on-the-real-30-day-period"><span class="header-section-number">4.5.1</span> Retroactive Out-of-Sample Validation on the Real 30-Day Period</h3>
<p>Rows from walk_report.csv corresponding exactly to the 14 May-7 Jun 2026 paper-trading period were extracted, using the specific model from each walk-forward window (not the final model applied retroactively, which would introduce partial leakage — see methodological note below).</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Real system (stale model)</th>
<th>Retrain (walk-forward OOS, same calendar period)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Trades</td>
<td>-</td>
<td>82</td>
</tr>
<tr class="even">
<td>Wins</td>
<td>-</td>
<td>55</td>
</tr>
<tr class="odd">
<td>Winrate</td>
<td>39.66%</td>
<td>67.07%</td>
</tr>
<tr class="even">
<td>Return</td>
<td>-0.98% ($1,000 -&gt; $990.24)</td>
<td>+5.97% ($7,989.11 -&gt; $8,465.93)</td>
</tr>
</tbody>
</table>
<p>Nearly 7 percentage points of return difference on the exact same market period, explained solely by trading with a stale model vs.&nbsp;one that had seen more recent data. This is the strongest confirmation that the 30-day paper-trading underperformance was caused by a stale model, not a structural system problem.</p>
<p>Methodological note — leakage detected and corrected during this analysis: a first validation attempt applied the final model (best_model.ubj, trained with train_end=2026-05-28) across the whole 14 May-25 Jun period, yielding an inflated winrate of 80% — inflated because that specific model had already seen data from the first half of the period (14-28 May) during its own training. This was corrected by using the results already reported by walk.py for each specific window (each model evaluated only on data it never saw), which is the methodology reported above.</p>
<p>Source: RESULTADO_MATRIZ_Y_CAUSA_30DIAS.md.</p>
</section>
</section>
<section id="live-paper-trading-day-0-onwards-27-jun-2026" class="level2" data-number="4.6">
<h2 data-number="4.6" class="anchored" data-anchor-id="live-paper-trading-day-0-onwards-27-jun-2026"><span class="header-section-number">4.6</span> Live Paper Trading — Day 0 Onwards (27 Jun 2026)</h2>
<p>Following the retrain and Railway Volume configuration on 27 Jun 2026, the system entered a clean paper trading run with the updated model, persistent state, and automated pipeline.</p>
<section id="second-retrain-25-jul-2026" class="level3" data-number="4.6.1">
<h3 data-number="4.6.1" class="anchored" data-anchor-id="second-retrain-25-jul-2026"><span class="header-section-number">4.6.1</span> Second Retrain — 25 Jul 2026</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Metric</th>
<th>Jun 27 retrain</th>
<th>Jul 25 retrain</th>
<th>Change</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Final Equity (walk-forward)</td>
<td>$8,589.78</td>
<td>$8,830.13</td>
<td>+2.8%</td>
</tr>
<tr class="even">
<td>Win rate</td>
<td>64.56%</td>
<td>64.44%</td>
<td>-0.12pp</td>
</tr>
<tr class="odd">
<td>CAGR</td>
<td>71.51%</td>
<td>70.93%</td>
<td>-0.58pp</td>
</tr>
<tr class="even">
<td>Max DD (daily)</td>
<td>-2.04%</td>
<td>-2.04%</td>
<td>identical</td>
</tr>
<tr class="odd">
<td>Trades</td>
<td>3,090</td>
<td>3,150</td>
<td>+60</td>
</tr>
<tr class="even">
<td>Dataset</td>
<td>34,972 rows to Jun 2026</td>
<td>same + Jul</td>
<td>extended</td>
</tr>
</tbody>
</table>
<p>The system is structurally stable across retrains. Metrics vary less than 1% despite 2+ months of additional bear market data — confirming robustness, not fragility.</p>
</section>
<section id="live-trade-ledger-27-jun-10-jul-2026" class="level3" data-number="4.6.2">
<h3 data-number="4.6.2" class="anchored" data-anchor-id="live-trade-ledger-27-jun-10-jul-2026"><span class="header-section-number">4.6.2</span> Live Trade Ledger (27 Jun – 10 Jul 2026)</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Date</th>
<th>Side</th>
<th style="text-align: right;">Entry</th>
<th>Result</th>
<th style="text-align: right;">PnL</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2026-06-27</td>
<td>Short</td>
<td style="text-align: right;">60,397</td>
<td>SL</td>
<td style="text-align: right;">-1.11</td>
</tr>
<tr class="even">
<td>2026-06-27</td>
<td>Short</td>
<td style="text-align: right;">60,550</td>
<td>SL</td>
<td style="text-align: right;">-1.12</td>
</tr>
<tr class="odd">
<td>2026-06-28</td>
<td>Short</td>
<td style="text-align: right;">59,957</td>
<td>SL</td>
<td style="text-align: right;">-1.21</td>
</tr>
<tr class="even">
<td>2026-06-28</td>
<td>Short</td>
<td style="text-align: right;">59,865</td>
<td>TP</td>
<td style="text-align: right;">+1.29</td>
</tr>
<tr class="odd">
<td>2026-06-29</td>
<td>Short</td>
<td style="text-align: right;">59,038</td>
<td>SL</td>
<td style="text-align: right;">-1.45</td>
</tr>
<tr class="even">
<td>2026-06-29</td>
<td>Short</td>
<td style="text-align: right;">59,549</td>
<td>SL</td>
<td style="text-align: right;">-1.55</td>
</tr>
<tr class="odd">
<td>2026-06-30</td>
<td>Short</td>
<td style="text-align: right;">59,593</td>
<td>TP</td>
<td style="text-align: right;">+2.38</td>
</tr>
<tr class="even">
<td>2026-06-30</td>
<td>Short</td>
<td style="text-align: right;">58,374</td>
<td>SL</td>
<td style="text-align: right;">-1.34</td>
</tr>
<tr class="odd">
<td>2026-07-01</td>
<td>Short</td>
<td style="text-align: right;">58,574</td>
<td>TP</td>
<td style="text-align: right;">+2.22</td>
</tr>
<tr class="even">
<td>2026-07-01</td>
<td>Short</td>
<td style="text-align: right;">59,306</td>
<td>TP</td>
<td style="text-align: right;">+2.33</td>
</tr>
<tr class="odd">
<td>2026-07-06</td>
<td>Short</td>
<td style="text-align: right;">63,551</td>
<td>TP</td>
<td style="text-align: right;">+1.57</td>
</tr>
<tr class="even">
<td>2026-07-06</td>
<td>Short</td>
<td style="text-align: right;">63,065</td>
<td>TP</td>
<td style="text-align: right;">+1.76</td>
</tr>
<tr class="odd">
<td>2026-07-08</td>
<td>Short</td>
<td style="text-align: right;">63,006</td>
<td>TP</td>
<td style="text-align: right;">+1.14</td>
</tr>
<tr class="even">
<td>2026-07-08</td>
<td>Short</td>
<td style="text-align: right;">61,985</td>
<td>SL</td>
<td style="text-align: right;">-0.67</td>
</tr>
<tr class="odd">
<td>2026-07-09</td>
<td>Short</td>
<td style="text-align: right;">62,303</td>
<td>SL</td>
<td style="text-align: right;">-1.37</td>
</tr>
<tr class="even">
<td>2026-07-09</td>
<td>Short</td>
<td style="text-align: right;">61,880</td>
<td>SL</td>
<td style="text-align: right;">-1.40</td>
</tr>
<tr class="odd">
<td>2026-07-10</td>
<td>Short</td>
<td style="text-align: right;">63,185</td>
<td>SL</td>
<td style="text-align: right;">-1.38</td>
</tr>
</tbody>
</table>
<p><strong>Summary:</strong> 17 trades, equity $1,000.08, MaxDD -0.34%. First 6 trades (warm-up, Jun 27-29): 1W/5L. Last 11 trades (Jun 30-Jul 10): 8W/3L (<strong>72.7% winrate</strong>) — consistent with the 64-75% historical expectation.</p>
</section>
<section id="simulated-performance-oct-2024-jul-2026" class="level3" data-number="4.6.3">
<h3 data-number="4.6.3" class="anchored" data-anchor-id="simulated-performance-oct-2024-jul-2026"><span class="header-section-number">4.6.3</span> Simulated Performance Oct 2024 – Jul 2026</h3>
<p>To contextualize the system’s behavior across the full recent market cycle (including the $60k→$109k bull run and subsequent bear), a simulation was run using the Jul 2026 model with max 2 trades/day selection by EV proxy:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Phase</th>
<th>BTC Return</th>
<th>S4 Return</th>
<th>Win Rate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Oct–Dec 2024 (BTC bull +45.5%)</td>
<td>+45.5%</td>
<td>+22.8%</td>
<td>73.6%</td>
</tr>
<tr class="even">
<td>Jan–Apr 2025 (lateral)</td>
<td>-0.3%</td>
<td>+39.4%</td>
<td>82.8%</td>
</tr>
<tr class="odd">
<td>May–Sep 2025 (bear -28%)</td>
<td>+21.3%</td>
<td>+31.6%</td>
<td>81.9%</td>
</tr>
<tr class="even">
<td>Oct 2025–Jul 2026 (bear)</td>
<td>-43.8%</td>
<td>+88.3%</td>
<td>73.4%</td>
</tr>
<tr class="odd">
<td><strong>Total (21 months)</strong></td>
<td><strong>+1.0%</strong></td>
<td><strong>+325.7%</strong></td>
<td><strong>77.0%</strong></td>
</tr>
</tbody>
</table>
<p>MaxDD across the full 21-month simulation: <strong>-0.60%</strong>.</p>
<p>Note: this simulation uses the Jul 2026 model retroactively — it is not a fully walk-forward OOS result for the pre-Jun 2026 period. It demonstrates the model’s behavior when kept current, not a prospective forecast. The walk-forward OOS result for the full dataset (2022-2026) is reported in the Snapshot table.</p>
</section>
</section>
<section id="rd-findings-economic-thesis-jul-2026" class="level2" data-number="4.7">
<h2 data-number="4.7" class="anchored" data-anchor-id="rd-findings-economic-thesis-jul-2026"><span class="header-section-number">4.7</span> R&amp;D Findings — Economic Thesis (Jul 2026)</h2>
<p>Three months of structured research investigated the source of S4’s edge across three hypotheses. Key visualizations:</p>
<section id="h1-serial-autocorrelation-rejected" class="level3" data-number="4.7.1">
<h3 data-number="4.7.1" class="anchored" data-anchor-id="h1-serial-autocorrelation-rejected"><span class="header-section-number">4.7.1</span> H1: Serial Autocorrelation (Rejected)</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/h1_autocorrelation.png" class="img-fluid figure-img"></p>
<figcaption>H1 — No momentum in 1h BTC returns</figcaption>
</figure>
</div>
<p>All volatility regimes show negative autocorrelation (mean-reversion, not momentum). The edge is not directional prediction — it is structural.</p>
</section>
<section id="h2-session-dependent-win-rate" class="level3" data-number="4.7.2">
<h3 data-number="4.7.2" class="anchored" data-anchor-id="h2-session-dependent-win-rate"><span class="header-section-number">4.7.2</span> H2: Session-Dependent Win Rate</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/h2_session_winrate.png" class="img-fluid figure-img"></p>
<figcaption>H2 — Win rate by hour and session</figcaption>
</figure>
</div>
<p>European session open (08h UTC) consistently shows the highest win rate. 90% of selected trades occur in 00h–02h UTC (Asian retail hours).</p>
</section>
<section id="pnl-attribution" class="level3" data-number="4.7.3">
<h3 data-number="4.7.3" class="anchored" data-anchor-id="pnl-attribution"><span class="header-section-number">4.7.3</span> PnL Attribution</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/pnl_attribution.png" class="img-fluid figure-img"></p>
<figcaption>PnL Attribution — 4 dimensions</figcaption>
</figure>
</div>
<p>Four key findings: (A) edge improves year-over-year with no decay signal, (B) model confidence is inversely correlated with win rate — p_up is a ranking signal, not a calibrated probability, (C) higher ATR linearly improves both win rate and Sharpe, (D) S4 outperforms BTC hold in all four market phases of Oct 2024–Jul 2026 including the +45.5% bull run.</p>


<!-- -->

</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./03-regime-research.html" class="pagination-link" aria-label="Regime Research">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Regime Research</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./05-deployment.html" class="pagination-link" aria-label="Deployment">
        <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Deployment</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb3" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu"># Live Validation</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">## Context</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>Diagnostic and mitigation session for statistical gaps identified in a prior institutional audit. The bot had been deployed on Railway for ~20 days with minimal activity (4 trades in 10 stable days). Source: CLAUDE_README_RESEARCH_SESSION_MAY25.md, author Eric Trevino, branch research/recalibration-meta-regime.</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="fu">## Production Bugs Fixed (on main)</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="fu">### Bug 1 — ev_gap_perc: 6,000x scale error</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>File: s4_deploy/s4_policy.py.</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>Problem: compared EV in dollars against the cost of a full BTC unit. Previous threshold approximately $185; correct threshold approximately $0.03. A trade with EV=$83 was being rejected because it did not reach $185.</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a><span class="in">~~~</span></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a><span class="in"># Before (bug)</span></span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a><span class="in">cost_only = (COMMISSION + SLIPPAGE) * close * 2</span></span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a><span class="in">if ev &lt; cost_only * (1 + EV_GAP_PERC):</span></span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a><span class="in"># After (correct - replicates walk.py line 416)</span></span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a><span class="in">stake0 = equity * POSITION_FRAC</span></span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a><span class="in">if ev &lt; stake0 * EV_GAP_PERC:</span></span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a><span class="in">~~~</span></span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a>Impact: the bot rejected approximately 100% of valid trades for 20 days. First candle post-fix: take=True dir=short ev=83.17 reason=ok.</span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a><span class="fu">### Bug 2 — LEVERAGE NameError</span></span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-29"><a href="#cb3-29" aria-hidden="true" tabindex="-1"></a>File: s4_deploy/trader.py. LEVERAGE was used in notional = d.stake * LEVERAGE but not imported from config.py. Fix: added to the import block.</span>
<span id="cb3-30"><a href="#cb3-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-31"><a href="#cb3-31" aria-hidden="true" tabindex="-1"></a><span class="fu">### Bug 3 — Malformed f-string in send_trade_closed</span></span>
<span id="cb3-32"><a href="#cb3-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-33"><a href="#cb3-33" aria-hidden="true" tabindex="-1"></a>File: s4_deploy/telegram_notifier.py.</span>
<span id="cb3-34"><a href="#cb3-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-35"><a href="#cb3-35" aria-hidden="true" tabindex="-1"></a><span class="in">~~~</span></span>
<span id="cb3-36"><a href="#cb3-36" aria-hidden="true" tabindex="-1"></a><span class="in"># Before (bug)</span></span>
<span id="cb3-37"><a href="#cb3-37" aria-hidden="true" tabindex="-1"></a><span class="in">f"(${tp:,.2f if outcome == 'tp' else sl:,.2f})"</span></span>
<span id="cb3-38"><a href="#cb3-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-39"><a href="#cb3-39" aria-hidden="true" tabindex="-1"></a><span class="in"># After</span></span>
<span id="cb3-40"><a href="#cb3-40" aria-hidden="true" tabindex="-1"></a><span class="in">f"(${(tp if win else sl):,.2f})"</span></span>
<span id="cb3-41"><a href="#cb3-41" aria-hidden="true" tabindex="-1"></a><span class="in">~~~</span></span>
<span id="cb3-42"><a href="#cb3-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-43"><a href="#cb3-43" aria-hidden="true" tabindex="-1"></a><span class="fu">### Feature Added — Daily Telegram Ledger Dump</span></span>
<span id="cb3-44"><a href="#cb3-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-45"><a href="#cb3-45" aria-hidden="true" tabindex="-1"></a>Files: s4_deploy/telegram_notifier.py, s4_deploy/trader.py. At 00:00 UTC daily, the bot sends the full ledger CSV via Telegram (protocol: copy-paste into Google Sheets). Implemented as a data-recovery mechanism during the ephemeral storage period; superseded by the Railway Volume configured on 27 Jun 2026 (<span class="in">`/app/persist`</span>), but retained as an independent audit trail.</span>
<span id="cb3-46"><a href="#cb3-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-47"><a href="#cb3-47" aria-hidden="true" tabindex="-1"></a><span class="fu">### Candle Synchronization Bug (Live Runtime Stability Patch, May 2026)</span></span>
<span id="cb3-48"><a href="#cb3-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-49"><a href="#cb3-49" aria-hidden="true" tabindex="-1"></a>Symptom: the model repeated the exact same p_up across multiple consecutive candles — not caused by the XGBoost model or feature engineering.</span>
<span id="cb3-50"><a href="#cb3-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-51"><a href="#cb3-51" aria-hidden="true" tabindex="-1"></a>Root cause: the main loop was querying Binance too close to the candle close boundary (approximately 2 seconds after UTC boundary), causing the API to return a still-partially-synced previous candle. Consequence: the bot reused the same closed candle multiple times, p_up appeared "stuck," the system rejected trades via prob_edge_low, and statistical sampling was partially contaminated.</span>
<span id="cb3-52"><a href="#cb3-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-53"><a href="#cb3-53" aria-hidden="true" tabindex="-1"></a>Fix: candle close buffer adjustment in the polling loop timing (implementation detail in trader.py).</span>
<span id="cb3-54"><a href="#cb3-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-55"><a href="#cb3-55" aria-hidden="true" tabindex="-1"></a><span class="fu">## Statistical Gaps — Status</span></span>
<span id="cb3-56"><a href="#cb3-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-57"><a href="#cb3-57" aria-hidden="true" tabindex="-1"></a><span class="fu">### Gap 2 — Kelly sizing miscalibration -&gt; CLOSED</span></span>
<span id="cb3-58"><a href="#cb3-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-59"><a href="#cb3-59" aria-hidden="true" tabindex="-1"></a>The ev_gap_perc bug (Bug 1 above) was the production manifestation of this gap. With the fix, sizing now operates exactly as in backtest.</span>
<span id="cb3-60"><a href="#cb3-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-61"><a href="#cb3-61" aria-hidden="true" tabindex="-1"></a><span class="fu">### Gap 3 — SPA Bootstrap complete -&gt; CLOSED</span></span>
<span id="cb3-62"><a href="#cb3-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-63"><a href="#cb3-63" aria-hidden="true" tabindex="-1"></a>File: statistics/spa_bootstrap_results.csv. SPA bootstrap (Hansen 2005) with stationary bootstrap (Politis and Romano, block_size=24h) against 500 benchmarks (250 random-threshold strategies, 125 permuted-feature strategies, 125 scaled buy-and-hold).</span>
<span id="cb3-64"><a href="#cb3-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-65"><a href="#cb3-65" aria-hidden="true" tabindex="-1"></a>Global result: SPA p=0.478 — fails for a structural reason (BTC rose 5x during 2022-2026, favoring buy-and-hold in this benchmark universe).</span>
<span id="cb3-66"><a href="#cb3-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-67"><a href="#cb3-67" aria-hidden="true" tabindex="-1"></a>SPA by regime (key finding) — S4 beats buy-and-hold in all three regimes, p=0.000:</span>
<span id="cb3-68"><a href="#cb3-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-69"><a href="#cb3-69" aria-hidden="true" tabindex="-1"></a>| Regime | Trades | Return S4 | Return B&amp;H | Ratio | p-value |</span>
<span id="cb3-70"><a href="#cb3-70" aria-hidden="true" tabindex="-1"></a>|---|---|---|---|---|---|</span>
<span id="cb3-71"><a href="#cb3-71" aria-hidden="true" tabindex="-1"></a>| BEAR | 3,202 | 0.004826 | 0.000910 | 5.3x | 0.0000 |</span>
<span id="cb3-72"><a href="#cb3-72" aria-hidden="true" tabindex="-1"></a>| LATERAL | 3,169 | 0.003741 | 0.000761 | 4.9x | 0.0000 |</span>
<span id="cb3-73"><a href="#cb3-73" aria-hidden="true" tabindex="-1"></a>| BULL | 9,571 | 0.004864 | 0.000887 | 5.5x | 0.0000 |</span>
<span id="cb3-74"><a href="#cb3-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-75"><a href="#cb3-75" aria-hidden="true" tabindex="-1"></a>Interpretation: the global SPA failure was a benchmark artifact (buy-and-hold during BTC's strongest historical bull run), not model data-snooping.</span>
<span id="cb3-76"><a href="#cb3-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-77"><a href="#cb3-77" aria-hidden="true" tabindex="-1"></a><span class="fu">### Gap 4 — Unstable features -&gt; CLOSED</span></span>
<span id="cb3-78"><a href="#cb3-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-79"><a href="#cb3-79" aria-hidden="true" tabindex="-1"></a>See Chapter 2 (Feature Significance) for the SHAP stability analysis that superseded the earlier XGBoost gain/cover finding.</span>
<span id="cb3-80"><a href="#cb3-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-81"><a href="#cb3-81" aria-hidden="true" tabindex="-1"></a><span class="fu">### Gap 5 — No microstructure features -&gt; IN PROGRESS</span></span>
<span id="cb3-82"><a href="#cb3-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-83"><a href="#cb3-83" aria-hidden="true" tabindex="-1"></a>Files: statistics/market_microstructure/open_interest_analysis.py, statistics/market_microstructure/artifacts/microstructure_features.csv.</span>
<span id="cb3-84"><a href="#cb3-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-85"><a href="#cb3-85" aria-hidden="true" tabindex="-1"></a>Fetcher implemented via OKX (Binance and Bybit IP-blocked from Mexico/datacenter). 697 rows generated, 30 days of history. Features: oi_change_1h, oi_change_8h, oi_zscore_24h, volume_oi_ratio, funding_rate (forward-filled), funding_sign, funding_extreme (1 if abs(funding) &gt; 2 historical std).</span>
<span id="cb3-86"><a href="#cb3-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-87"><a href="#cb3-87" aria-hidden="true" tabindex="-1"></a>Pending: integrate into the day-30 model retrain — will require reconstructing the historical dataset with these features back to 2022 via OKX history.</span>
<span id="cb3-88"><a href="#cb3-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-89"><a href="#cb3-89" aria-hidden="true" tabindex="-1"></a><span class="fu">## The 30-Day Live Paper Trading Result and Root Cause</span></span>
<span id="cb3-90"><a href="#cb3-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-91"><a href="#cb3-91" aria-hidden="true" tabindex="-1"></a><span class="fu">### The Real Result</span></span>
<span id="cb3-92"><a href="#cb3-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-93"><a href="#cb3-93" aria-hidden="true" tabindex="-1"></a>| Metric | Value |</span>
<span id="cb3-94"><a href="#cb3-94" aria-hidden="true" tabindex="-1"></a>|---|---|</span>
<span id="cb3-95"><a href="#cb3-95" aria-hidden="true" tabindex="-1"></a>| Period | 14 May - 25 Jun 2026 |</span>
<span id="cb3-96"><a href="#cb3-96" aria-hidden="true" tabindex="-1"></a>| Return | -0.98% ($1,000 -&gt; $990.24) |</span>
<span id="cb3-97"><a href="#cb3-97" aria-hidden="true" tabindex="-1"></a>| Winrate | 39.66% (vs. 74.22% historically expected for this regime) |</span>
<span id="cb3-98"><a href="#cb3-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-99"><a href="#cb3-99" aria-hidden="true" tabindex="-1"></a><span class="fu">### Hypothesis Tested and Rejected: Low Volatility</span></span>
<span id="cb3-100"><a href="#cb3-100" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-101"><a href="#cb3-101" aria-hidden="true" tabindex="-1"></a>User hypothesis: the loss was due to low market volatility (a "quiet" regime).</span>
<span id="cb3-102"><a href="#cb3-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-103"><a href="#cb3-103" aria-hidden="true" tabindex="-1"></a>Verified with real data (606 candles, 14 May-25 Jun 2026):</span>
<span id="cb3-104"><a href="#cb3-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-105"><a href="#cb3-105" aria-hidden="true" tabindex="-1"></a>| Volatility category | Frequency |</span>
<span id="cb3-106"><a href="#cb3-106" aria-hidden="true" tabindex="-1"></a>|---|---|</span>
<span id="cb3-107"><a href="#cb3-107" aria-hidden="true" tabindex="-1"></a>| HIGH_VOL | 244 candles (40.3%) - most frequent |</span>
<span id="cb3-108"><a href="#cb3-108" aria-hidden="true" tabindex="-1"></a>| MIDLOW_VOL | 136 candles (22.4%) |</span>
<span id="cb3-109"><a href="#cb3-109" aria-hidden="true" tabindex="-1"></a>| MIDHIGH_VOL | 118 candles (19.5%) |</span>
<span id="cb3-110"><a href="#cb3-110" aria-hidden="true" tabindex="-1"></a>| LOW_VOL | 108 candles (17.8%) - least frequent |</span>
<span id="cb3-111"><a href="#cb3-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-112"><a href="#cb3-112" aria-hidden="true" tabindex="-1"></a>ATR% average for the period: 0.6461% vs. historical average 0.7406% -&gt; percentile 47.3 (essentially the median). Hypothesis rejected — volatility was normal, and HIGH_VOL was in fact the single most frequent category.</span>
<span id="cb3-113"><a href="#cb3-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-114"><a href="#cb3-114" aria-hidden="true" tabindex="-1"></a>Trend distribution for the period: BEAR_TREND 73.0% (442 candles), BEAR_RALLY 19.3% (117), BULL_TREND 7.8% (47) — a sustained bear market with normal-to-high volatility, not a low-volatility sideways market.</span>
<span id="cb3-115"><a href="#cb3-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-116"><a href="#cb3-116" aria-hidden="true" tabindex="-1"></a><span class="fu">### Additional Finding: Directional Efficiency, Not Candle Volatility</span></span>
<span id="cb3-117"><a href="#cb3-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-118"><a href="#cb3-118" aria-hidden="true" tabindex="-1"></a>After ruling out low candle-level volatility (ATR normal, percentile 47) and ruling out model behavior drift (p_up distribution nearly identical to historical pattern for this regime: mean 0.4531 real vs. 0.4411 historical), a third variable was investigated: directional efficiency of movement over multi-hour windows (the system's real resolution horizon, H=12 candles).</span>
<span id="cb3-119"><a href="#cb3-119" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-120"><a href="#cb3-120" aria-hidden="true" tabindex="-1"></a>| | Mean 12h return | Std |</span>
<span id="cb3-121"><a href="#cb3-121" aria-hidden="true" tabindex="-1"></a>|---|---|---|</span>
<span id="cb3-122"><a href="#cb3-122" aria-hidden="true" tabindex="-1"></a>| Real period (May-Jun 2026) | -0.471% | 1.433% |</span>
<span id="cb3-123"><a href="#cb3-123" aria-hidden="true" tabindex="-1"></a>| Historical, same regime (BEAR_TREND + normal vol) | +0.231% | 4.968% |</span>
<span id="cb3-124"><a href="#cb3-124" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-125"><a href="#cb3-125" aria-hidden="true" tabindex="-1"></a>The 12-hour return standard deviation during the real period was 3.5x lower than the historical pattern for the same regime (1.433% vs. 4.968%), despite 1h ATR looking normal.</span>
<span id="cb3-126"><a href="#cb3-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-127"><a href="#cb3-127" aria-hidden="true" tabindex="-1"></a>Interpretation: 1h ATR measures range within each individual candle but does not capture whether those candles move directionally and cumulatively, or "breathe" back and forth without net progress over longer windows. The period had normal-sized individual candles but high "noise" with low "net advance" over 12h windows — exactly the lethal pattern for a Triple-Barrier system with TP=2xATR: it needs sustained net movement of 2x the entry candle's ATR, and when the market moves with noise but without sustained directional coherence, SL (which only needs 0.8xATR) triggers disproportionately more than TP — a pattern none of the metrics used in the original diagnosis (1h ATR, trend regime, model behavior) could detect.</span>
<span id="cb3-128"><a href="#cb3-128" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-129"><a href="#cb3-129" aria-hidden="true" tabindex="-1"></a>Implication for future work: a "directional efficiency" metric (e.g., the ratio of net movement over N candles to the sum of absolute candle-to-candle movements — similar to Kaufman's Efficiency Ratio) may be a more informative regime feature than single-candle ATR or EMA/DMA trend classification, and is a candidate for future research before permanently ruling out a regime filter based on this dimension.</span>
<span id="cb3-130"><a href="#cb3-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-131"><a href="#cb3-131" aria-hidden="true" tabindex="-1"></a>Final combined root cause: (a) a stale model that never saw this specific period, and (b) low directional efficiency over 12h windows (high noise, low net advance) that no regime metric used prior to this analysis captured. Together these explain the observed 39.66% winrate vs. 74.22% historically expected for the same trend/volatility regime.</span>
<span id="cb3-132"><a href="#cb3-132" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-133"><a href="#cb3-133" aria-hidden="true" tabindex="-1"></a><span class="fu">## Retrain Validation — Final Result (26 Jun 2026)</span></span>
<span id="cb3-134"><a href="#cb3-134" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-135"><a href="#cb3-135" aria-hidden="true" tabindex="-1"></a>After repairing the dataset (a May data gap was filled) and re-running walk.py in full:</span>
<span id="cb3-136"><a href="#cb3-136" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-137"><a href="#cb3-137" aria-hidden="true" tabindex="-1"></a>| Metric | Retrain | Original Baseline |</span>
<span id="cb3-138"><a href="#cb3-138" aria-hidden="true" tabindex="-1"></a>|---|---|---|</span>
<span id="cb3-139"><a href="#cb3-139" aria-hidden="true" tabindex="-1"></a>| Final Equity | $8,465.93 | $7,989 (+6%) |</span>
<span id="cb3-140"><a href="#cb3-140" aria-hidden="true" tabindex="-1"></a>| Win rate | 64.72% | 64.66% (essentially unchanged) |</span>
<span id="cb3-141"><a href="#cb3-141" aria-hidden="true" tabindex="-1"></a>| CAGR | 72.10% | identical to baseline |</span>
<span id="cb3-142"><a href="#cb3-142" aria-hidden="true" tabindex="-1"></a>| Max DD (daily) | -2.04% | identical to baseline |</span>
<span id="cb3-143"><a href="#cb3-143" aria-hidden="true" tabindex="-1"></a>| Trades | 3,050 | 2,968 (+82, from the extra 2 months) |</span>
<span id="cb3-144"><a href="#cb3-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-145"><a href="#cb3-145" aria-hidden="true" tabindex="-1"></a>The retrain replicates historical behavior almost exactly, confirming the architecture, labeling, and model are structurally robust — the problem was never structural.</span>
<span id="cb3-146"><a href="#cb3-146" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-147"><a href="#cb3-147" aria-hidden="true" tabindex="-1"></a><span class="fu">### Retroactive Out-of-Sample Validation on the Real 30-Day Period</span></span>
<span id="cb3-148"><a href="#cb3-148" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-149"><a href="#cb3-149" aria-hidden="true" tabindex="-1"></a>Rows from walk_report.csv corresponding exactly to the 14 May-7 Jun 2026 paper-trading period were extracted, using the specific model from each walk-forward window (not the final model applied retroactively, which would introduce partial leakage — see methodological note below).</span>
<span id="cb3-150"><a href="#cb3-150" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-151"><a href="#cb3-151" aria-hidden="true" tabindex="-1"></a>| | Real system (stale model) | Retrain (walk-forward OOS, same calendar period) |</span>
<span id="cb3-152"><a href="#cb3-152" aria-hidden="true" tabindex="-1"></a>|---|---|---|</span>
<span id="cb3-153"><a href="#cb3-153" aria-hidden="true" tabindex="-1"></a>| Trades | - | 82 |</span>
<span id="cb3-154"><a href="#cb3-154" aria-hidden="true" tabindex="-1"></a>| Wins | - | 55 |</span>
<span id="cb3-155"><a href="#cb3-155" aria-hidden="true" tabindex="-1"></a>| Winrate | 39.66% | 67.07% |</span>
<span id="cb3-156"><a href="#cb3-156" aria-hidden="true" tabindex="-1"></a>| Return | -0.98% ($1,000 -&gt; $990.24) | +5.97% ($7,989.11 -&gt; $8,465.93) |</span>
<span id="cb3-157"><a href="#cb3-157" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-158"><a href="#cb3-158" aria-hidden="true" tabindex="-1"></a>Nearly 7 percentage points of return difference on the exact same market period, explained solely by trading with a stale model vs. one that had seen more recent data. This is the strongest confirmation that the 30-day paper-trading underperformance was caused by a stale model, not a structural system problem.</span>
<span id="cb3-159"><a href="#cb3-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-160"><a href="#cb3-160" aria-hidden="true" tabindex="-1"></a>Methodological note — leakage detected and corrected during this analysis: a first validation attempt applied the final model (best_model.ubj, trained with train_end=2026-05-28) across the whole 14 May-25 Jun period, yielding an inflated winrate of 80% — inflated because that specific model had already seen data from the first half of the period (14-28 May) during its own training. This was corrected by using the results already reported by walk.py for each specific window (each model evaluated only on data it never saw), which is the methodology reported above.</span>
<span id="cb3-161"><a href="#cb3-161" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-162"><a href="#cb3-162" aria-hidden="true" tabindex="-1"></a>Source: RESULTADO_MATRIZ_Y_CAUSA_30DIAS.md.</span>
<span id="cb3-163"><a href="#cb3-163" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-164"><a href="#cb3-164" aria-hidden="true" tabindex="-1"></a><span class="fu">## Live Paper Trading — Day 0 Onwards (27 Jun 2026)</span></span>
<span id="cb3-165"><a href="#cb3-165" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-166"><a href="#cb3-166" aria-hidden="true" tabindex="-1"></a>Following the retrain and Railway Volume configuration on 27 Jun 2026,</span>
<span id="cb3-167"><a href="#cb3-167" aria-hidden="true" tabindex="-1"></a>the system entered a clean paper trading run with the updated model,</span>
<span id="cb3-168"><a href="#cb3-168" aria-hidden="true" tabindex="-1"></a>persistent state, and automated pipeline.</span>
<span id="cb3-169"><a href="#cb3-169" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-170"><a href="#cb3-170" aria-hidden="true" tabindex="-1"></a><span class="fu">### Second Retrain — 25 Jul 2026</span></span>
<span id="cb3-171"><a href="#cb3-171" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-172"><a href="#cb3-172" aria-hidden="true" tabindex="-1"></a>| Metric | Jun 27 retrain | Jul 25 retrain | Change |</span>
<span id="cb3-173"><a href="#cb3-173" aria-hidden="true" tabindex="-1"></a>|---|---|---|---|</span>
<span id="cb3-174"><a href="#cb3-174" aria-hidden="true" tabindex="-1"></a>| Final Equity (walk-forward) | $8,589.78 | $8,830.13 | +2.8% |</span>
<span id="cb3-175"><a href="#cb3-175" aria-hidden="true" tabindex="-1"></a>| Win rate | 64.56% | 64.44% | -0.12pp |</span>
<span id="cb3-176"><a href="#cb3-176" aria-hidden="true" tabindex="-1"></a>| CAGR | 71.51% | 70.93% | -0.58pp |</span>
<span id="cb3-177"><a href="#cb3-177" aria-hidden="true" tabindex="-1"></a>| Max DD (daily) | -2.04% | -2.04% | identical |</span>
<span id="cb3-178"><a href="#cb3-178" aria-hidden="true" tabindex="-1"></a>| Trades | 3,090 | 3,150 | +60 |</span>
<span id="cb3-179"><a href="#cb3-179" aria-hidden="true" tabindex="-1"></a>| Dataset | 34,972 rows to Jun 2026 | same + Jul | extended |</span>
<span id="cb3-180"><a href="#cb3-180" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-181"><a href="#cb3-181" aria-hidden="true" tabindex="-1"></a>The system is structurally stable across retrains. Metrics vary less</span>
<span id="cb3-182"><a href="#cb3-182" aria-hidden="true" tabindex="-1"></a>than 1% despite 2+ months of additional bear market data — confirming</span>
<span id="cb3-183"><a href="#cb3-183" aria-hidden="true" tabindex="-1"></a>robustness, not fragility.</span>
<span id="cb3-184"><a href="#cb3-184" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-185"><a href="#cb3-185" aria-hidden="true" tabindex="-1"></a><span class="fu">### Live Trade Ledger (27 Jun – 10 Jul 2026)</span></span>
<span id="cb3-186"><a href="#cb3-186" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-187"><a href="#cb3-187" aria-hidden="true" tabindex="-1"></a>| Date | Side | Entry | Result | PnL |</span>
<span id="cb3-188"><a href="#cb3-188" aria-hidden="true" tabindex="-1"></a>|------|------|------:|--------|----:|</span>
<span id="cb3-189"><a href="#cb3-189" aria-hidden="true" tabindex="-1"></a>| 2026-06-27 | Short | 60,397 | SL | -1.11 |</span>
<span id="cb3-190"><a href="#cb3-190" aria-hidden="true" tabindex="-1"></a>| 2026-06-27 | Short | 60,550 | SL | -1.12 |</span>
<span id="cb3-191"><a href="#cb3-191" aria-hidden="true" tabindex="-1"></a>| 2026-06-28 | Short | 59,957 | SL | -1.21 |</span>
<span id="cb3-192"><a href="#cb3-192" aria-hidden="true" tabindex="-1"></a>| 2026-06-28 | Short | 59,865 | TP | +1.29 |</span>
<span id="cb3-193"><a href="#cb3-193" aria-hidden="true" tabindex="-1"></a>| 2026-06-29 | Short | 59,038 | SL | -1.45 |</span>
<span id="cb3-194"><a href="#cb3-194" aria-hidden="true" tabindex="-1"></a>| 2026-06-29 | Short | 59,549 | SL | -1.55 |</span>
<span id="cb3-195"><a href="#cb3-195" aria-hidden="true" tabindex="-1"></a>| 2026-06-30 | Short | 59,593 | TP | +2.38 |</span>
<span id="cb3-196"><a href="#cb3-196" aria-hidden="true" tabindex="-1"></a>| 2026-06-30 | Short | 58,374 | SL | -1.34 |</span>
<span id="cb3-197"><a href="#cb3-197" aria-hidden="true" tabindex="-1"></a>| 2026-07-01 | Short | 58,574 | TP | +2.22 |</span>
<span id="cb3-198"><a href="#cb3-198" aria-hidden="true" tabindex="-1"></a>| 2026-07-01 | Short | 59,306 | TP | +2.33 |</span>
<span id="cb3-199"><a href="#cb3-199" aria-hidden="true" tabindex="-1"></a>| 2026-07-06 | Short | 63,551 | TP | +1.57 |</span>
<span id="cb3-200"><a href="#cb3-200" aria-hidden="true" tabindex="-1"></a>| 2026-07-06 | Short | 63,065 | TP | +1.76 |</span>
<span id="cb3-201"><a href="#cb3-201" aria-hidden="true" tabindex="-1"></a>| 2026-07-08 | Short | 63,006 | TP | +1.14 |</span>
<span id="cb3-202"><a href="#cb3-202" aria-hidden="true" tabindex="-1"></a>| 2026-07-08 | Short | 61,985 | SL | -0.67 |</span>
<span id="cb3-203"><a href="#cb3-203" aria-hidden="true" tabindex="-1"></a>| 2026-07-09 | Short | 62,303 | SL | -1.37 |</span>
<span id="cb3-204"><a href="#cb3-204" aria-hidden="true" tabindex="-1"></a>| 2026-07-09 | Short | 61,880 | SL | -1.40 |</span>
<span id="cb3-205"><a href="#cb3-205" aria-hidden="true" tabindex="-1"></a>| 2026-07-10 | Short | 63,185 | SL | -1.38 |</span>
<span id="cb3-206"><a href="#cb3-206" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-207"><a href="#cb3-207" aria-hidden="true" tabindex="-1"></a>**Summary:** 17 trades, equity $1,000.08, MaxDD -0.34%.</span>
<span id="cb3-208"><a href="#cb3-208" aria-hidden="true" tabindex="-1"></a>First 6 trades (warm-up, Jun 27-29): 1W/5L.</span>
<span id="cb3-209"><a href="#cb3-209" aria-hidden="true" tabindex="-1"></a>Last 11 trades (Jun 30-Jul 10): 8W/3L (**72.7% winrate**) — consistent</span>
<span id="cb3-210"><a href="#cb3-210" aria-hidden="true" tabindex="-1"></a>with the 64-75% historical expectation.</span>
<span id="cb3-211"><a href="#cb3-211" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-212"><a href="#cb3-212" aria-hidden="true" tabindex="-1"></a><span class="fu">### Simulated Performance Oct 2024 – Jul 2026</span></span>
<span id="cb3-213"><a href="#cb3-213" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-214"><a href="#cb3-214" aria-hidden="true" tabindex="-1"></a>To contextualize the system's behavior across the full recent market</span>
<span id="cb3-215"><a href="#cb3-215" aria-hidden="true" tabindex="-1"></a>cycle (including the $60k→$109k bull run and subsequent bear), a</span>
<span id="cb3-216"><a href="#cb3-216" aria-hidden="true" tabindex="-1"></a>simulation was run using the Jul 2026 model with max 2 trades/day</span>
<span id="cb3-217"><a href="#cb3-217" aria-hidden="true" tabindex="-1"></a>selection by EV proxy:</span>
<span id="cb3-218"><a href="#cb3-218" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-219"><a href="#cb3-219" aria-hidden="true" tabindex="-1"></a>| Phase | BTC Return | S4 Return | Win Rate |</span>
<span id="cb3-220"><a href="#cb3-220" aria-hidden="true" tabindex="-1"></a>|---|---|---|---|</span>
<span id="cb3-221"><a href="#cb3-221" aria-hidden="true" tabindex="-1"></a>| Oct–Dec 2024 (BTC bull +45.5%) | +45.5% | +22.8% | 73.6% |</span>
<span id="cb3-222"><a href="#cb3-222" aria-hidden="true" tabindex="-1"></a>| Jan–Apr 2025 (lateral) | -0.3% | +39.4% | 82.8% |</span>
<span id="cb3-223"><a href="#cb3-223" aria-hidden="true" tabindex="-1"></a>| May–Sep 2025 (bear -28%) | +21.3% | +31.6% | 81.9% |</span>
<span id="cb3-224"><a href="#cb3-224" aria-hidden="true" tabindex="-1"></a>| Oct 2025–Jul 2026 (bear) | -43.8% | +88.3% | 73.4% |</span>
<span id="cb3-225"><a href="#cb3-225" aria-hidden="true" tabindex="-1"></a>| **Total (21 months)** | **+1.0%** | **+325.7%** | **77.0%** |</span>
<span id="cb3-226"><a href="#cb3-226" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-227"><a href="#cb3-227" aria-hidden="true" tabindex="-1"></a>MaxDD across the full 21-month simulation: **-0.60%**.</span>
<span id="cb3-228"><a href="#cb3-228" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-229"><a href="#cb3-229" aria-hidden="true" tabindex="-1"></a>Note: this simulation uses the Jul 2026 model retroactively — it is</span>
<span id="cb3-230"><a href="#cb3-230" aria-hidden="true" tabindex="-1"></a>not a fully walk-forward OOS result for the pre-Jun 2026 period.</span>
<span id="cb3-231"><a href="#cb3-231" aria-hidden="true" tabindex="-1"></a>It demonstrates the model's behavior when kept current, not a</span>
<span id="cb3-232"><a href="#cb3-232" aria-hidden="true" tabindex="-1"></a>prospective forecast. The walk-forward OOS result for the full</span>
<span id="cb3-233"><a href="#cb3-233" aria-hidden="true" tabindex="-1"></a>dataset (2022-2026) is reported in the Snapshot table.</span>
<span id="cb3-234"><a href="#cb3-234" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-235"><a href="#cb3-235" aria-hidden="true" tabindex="-1"></a><span class="fu">## R&amp;D Findings — Economic Thesis (Jul 2026)</span></span>
<span id="cb3-236"><a href="#cb3-236" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-237"><a href="#cb3-237" aria-hidden="true" tabindex="-1"></a>Three months of structured research investigated the source of S4's edge</span>
<span id="cb3-238"><a href="#cb3-238" aria-hidden="true" tabindex="-1"></a>across three hypotheses. Key visualizations:</span>
<span id="cb3-239"><a href="#cb3-239" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-240"><a href="#cb3-240" aria-hidden="true" tabindex="-1"></a><span class="fu">### H1: Serial Autocorrelation (Rejected)</span></span>
<span id="cb3-241"><a href="#cb3-241" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-242"><a href="#cb3-242" aria-hidden="true" tabindex="-1"></a><span class="al">![H1 — No momentum in 1h BTC returns](figures/h1_autocorrelation.png)</span></span>
<span id="cb3-243"><a href="#cb3-243" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-244"><a href="#cb3-244" aria-hidden="true" tabindex="-1"></a>All volatility regimes show negative autocorrelation (mean-reversion,</span>
<span id="cb3-245"><a href="#cb3-245" aria-hidden="true" tabindex="-1"></a>not momentum). The edge is not directional prediction — it is structural.</span>
<span id="cb3-246"><a href="#cb3-246" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-247"><a href="#cb3-247" aria-hidden="true" tabindex="-1"></a><span class="fu">### H2: Session-Dependent Win Rate</span></span>
<span id="cb3-248"><a href="#cb3-248" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-249"><a href="#cb3-249" aria-hidden="true" tabindex="-1"></a><span class="al">![H2 — Win rate by hour and session](figures/h2_session_winrate.png)</span></span>
<span id="cb3-250"><a href="#cb3-250" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-251"><a href="#cb3-251" aria-hidden="true" tabindex="-1"></a>European session open (08h UTC) consistently shows the highest win rate.</span>
<span id="cb3-252"><a href="#cb3-252" aria-hidden="true" tabindex="-1"></a>90% of selected trades occur in 00h–02h UTC (Asian retail hours).</span>
<span id="cb3-253"><a href="#cb3-253" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-254"><a href="#cb3-254" aria-hidden="true" tabindex="-1"></a><span class="fu">### PnL Attribution</span></span>
<span id="cb3-255"><a href="#cb3-255" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-256"><a href="#cb3-256" aria-hidden="true" tabindex="-1"></a><span class="al">![PnL Attribution — 4 dimensions](figures/pnl_attribution.png)</span></span>
<span id="cb3-257"><a href="#cb3-257" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-258"><a href="#cb3-258" aria-hidden="true" tabindex="-1"></a>Four key findings: (A) edge improves year-over-year with no decay signal,</span>
<span id="cb3-259"><a href="#cb3-259" aria-hidden="true" tabindex="-1"></a>(B) model confidence is inversely correlated with win rate — p_up is a</span>
<span id="cb3-260"><a href="#cb3-260" aria-hidden="true" tabindex="-1"></a>ranking signal, not a calibrated probability, (C) higher ATR linearly</span>
<span id="cb3-261"><a href="#cb3-261" aria-hidden="true" tabindex="-1"></a>improves both win rate and Sharpe, (D) S4 outperforms BTC hold in all</span>
<span id="cb3-262"><a href="#cb3-262" aria-hidden="true" tabindex="-1"></a>four market phases of Oct 2024–Jul 2026 including the +45.5% bull run.</span></code><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/erictvillarreal/RoboTrader812/edit/main/04-live-validation.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/erictvillarreal/RoboTrader812/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer><script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>