<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.39">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Eric Trevino">
<meta name="dcterms.date" content="2026-07-29">

<title>S4BTC</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./01-architecture.html" rel="next">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-0626ff4d7a71b55c8707dcae1d04a9b6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-0f1d7832f862a9a05de4b1f937104ab7.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


</head>

<body class="nav-sidebar floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">S4BTC</span>
    </a>
  </div>
        <div class="quarto-navbar-tools tools-end">
    <a href="https://github.com/erictvillarreal/RoboTrader812" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
          <div id="quarto-search" class="" title="Search"></div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./index.html">Executive Summary</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Executive Summary</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-architecture.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">System Architecture</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-statistical-due-diligence.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Statistical Due Diligence</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-regime-research.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Regime Research</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-live-validation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Live Validation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-deployment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Deployment</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-roadmap.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Roadmap — Open Gaps &amp; Next Steps</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./99-appendix-data-sources.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Appendix — Data Source Reconciliation</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#executive-summary" id="toc-executive-summary" class="nav-link active" data-scroll-target="#executive-summary">Executive Summary</a>
  <ul class="collapse">
  <li><a href="#what-is-s4" id="toc-what-is-s4" class="nav-link" data-scroll-target="#what-is-s4">What is S4</a></li>
  <li><a href="#current-classification" id="toc-current-classification" class="nav-link" data-scroll-target="#current-classification">Current Classification</a></li>
  <li><a href="#snapshot-last-validated-run-26-jun-2026-retrain" id="toc-snapshot-last-validated-run-26-jun-2026-retrain" class="nav-link" data-scroll-target="#snapshot-last-validated-run-26-jun-2026-retrain">Snapshot (last validated run — 26 Jun 2026 retrain)</a></li>
  <li><a href="#key-findings-validated-cross-checked" id="toc-key-findings-validated-cross-checked" class="nav-link" data-scroll-target="#key-findings-validated-cross-checked">Key Findings (validated, cross-checked)</a></li>
  <li><a href="#how-to-read-this-report" id="toc-how-to-read-this-report" class="nav-link" data-scroll-target="#how-to-read-this-report">How to Read This Report</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/erictvillarreal/RoboTrader812/edit/main/index.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/erictvillarreal/RoboTrader812/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">S4BTC</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
<p class="subtitle lead">Institutional Research &amp; Deployment Report</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Eric Trevino </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">July 29, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="executive-summary" class="level1 unnumbered">
<h1 class="unnumbered">Executive Summary</h1>
<section id="what-is-s4" class="level2">
<h2 class="anchored" data-anchor-id="what-is-s4">What is S4</h2>
<p>S4 is a systematic short-term trading engine for BTCUSDT Perpetual Futures, built on a structural mathematical edge in perpetual futures markets.</p>
<p><strong>The core mechanism:</strong> with TP=2.0×ATR and SL=0.8×ATR, the geometric probability of a short winning in a random walk is 71.4%. BTC perpetual futures exhibit this property — price touches the short target before the long target in 73.5% of 1h candles historically. An EV-gap filter selects the highest-EV candidates each day. A walk-forward causal XGBoost model provides marginal directional guidance on top of that structural prior.</p>
<p><strong>Simulated result (Oct 2024 – Jul 2026, 21 months):</strong> +325.7% vs.&nbsp;BTC hold +1.0%, MaxDD -0.60%, winrate 77.0%. Positive in all regimes tested including the $60k→$109k bull run.</p>
</section>
<section id="current-classification" class="level2">
<h2 class="anchored" data-anchor-id="current-classification">Current Classification</h2>
<blockquote class="blockquote">
<p><strong>“Research-grade promising systematic strategy.”</strong> Not yet: institutional production system. Substantially beyond: hobby backtesting.</p>
</blockquote>
<p>Source: <code>statistics/README.md</code>, Final Conclusions.</p>
<blockquote class="blockquote">
<p><strong>Operational status (as of 28 Jul 2026):</strong> Paper trading on Railway — live and running. Last retrain: 25 Jul 2026 (<code>retrain_pipeline.py</code>, automated, equity $8,830, winrate 64.44%). Railway Volume (<code>/app/persist</code>, 500 MB) — state, model, and ledger persist across redeploys. <strong>Capital deployment decision pending: 27 Sep 2026</strong> (3-month clean paper trading checkpoint).</p>
</blockquote>
</section>
<section id="snapshot-last-validated-run-26-jun-2026-retrain" class="level2">
<h2 class="anchored" data-anchor-id="snapshot-last-validated-run-26-jun-2026-retrain">Snapshot (last validated run — 26 Jun 2026 retrain)</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Metric</th>
<th>Value</th>
<th>Source</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Equity final (walk-forward, Jul 2026 retrain)</td>
<td><strong>$8,830</strong> (baseline: $7,989; +10.5%)</td>
<td><code>walk_summary.json</code>, 25 Jul 2026 retrain</td>
</tr>
<tr class="even">
<td>CAGR</td>
<td><strong>70.93%</strong></td>
<td><code>walk_summary.json</code>, 25 Jul 2026 retrain</td>
</tr>
<tr class="odd">
<td>Win rate (baseline, no regime filter)</td>
<td><strong>64.44%</strong></td>
<td><code>walk_summary.json</code>, 25 Jul 2026 retrain</td>
</tr>
<tr class="even">
<td>Live performance (Oct 2024 – Jul 2026, 21 months)</td>
<td><strong>+325.7%</strong> (winrate 77.0%, MaxDD -0.60%)</td>
<td><code>r_and_d/02_pnl_attribution/</code></td>
</tr>
<tr class="odd">
<td>BTC hold same period</td>
<td><strong>+1.0%</strong></td>
<td>OKX BTCUSDT price</td>
</tr>
<tr class="even">
<td>Win rate (BULL_AND_HIGHVOL filter)</td>
<td>72.61%</td>
<td><code>s4_enhancement/README.md</code></td>
</tr>
<tr class="odd">
<td>Sharpe-like (baseline)</td>
<td>0.6395</td>
<td><code>statistics/whites_reality_check_report.csv</code></td>
</tr>
<tr class="even">
<td>Sharpe-like (BULL_AND_HIGHVOL filter)</td>
<td>0.8534</td>
<td><code>s4_enhancement/integrated_meta_walk_report.csv</code></td>
</tr>
<tr class="odd">
<td>Max Drawdown (daily)</td>
<td>-2.04%</td>
<td><code>walk_summary.json</code>, <code>statistics/README.md</code> (consistent)</td>
</tr>
<tr class="even">
<td>Max Drawdown (BULL_AND_HIGHVOL filter)</td>
<td>-7.40%</td>
<td><code>s4_enhancement/README.md</code></td>
</tr>
<tr class="odd">
<td>30-day live paper trading (real, May–Jun 2026)</td>
<td>-0.98% (winrate 39.66%)</td>
<td><code>RESULTADO_MATRIZ_Y_CAUSA_30DIAS.md</code></td>
</tr>
<tr class="even">
<td>30-day retroactive OOS retrain (same period)</td>
<td>+5.97% (winrate 67.07%)</td>
<td><code>RESULTADO_MATRIZ_Y_CAUSA_30DIAS.md</code></td>
</tr>
<tr class="odd">
<td>Full Kelly estimate</td>
<td>0.505</td>
<td><code>statistics/fractional_kelly_report.csv</code></td>
</tr>
<tr class="even">
<td>White’s Reality Check p-value</td>
<td>0.506 (FAIL)</td>
<td><code>statistics/whites_reality_check_report.csv</code></td>
</tr>
<tr class="odd">
<td>SPA sign-flip p-value</td>
<td>0.000 (PASS)</td>
<td><code>statistics/README.md</code></td>
</tr>
</tbody>
</table>
<p>Note: rows flagged “conflicting values” have two or more source documents reporting different numbers for the same metric. These are <strong>not yet reconciled</strong> — see the <a href="./99-appendix-data-sources.html">Appendix</a> for the full side-by-side and a note to revisit.</p>
</section>
<section id="key-findings-validated-cross-checked" class="level2">
<h2 class="anchored" data-anchor-id="key-findings-validated-cross-checked">Key Findings (validated, cross-checked)</h2>
<ol type="1">
<li><p><strong>The edge is statistically real and survives adversarial testing.</strong> A randomized-label sanity check — the most direct test for model memorization — collapses F1 from 0.218 to 0.014 and recall to 0.009 when trade labels are shuffled. The model extracts genuine signal from price structure, not noise. SPA sign-flip p-value: 0.000 across all three market regimes (bear, lateral, bull) independently.</p></li>
<li><p><strong>The edge holds across market regimes — including bear markets.</strong> S4 generates 4.9x–5.5x the return of a buy-and-hold benchmark in bear, lateral, and bull conditions simultaneously, each at p=0.000. This was the key result that elevated S4 from a bull-market artifact to a structurally robust strategy.</p></li>
<li><p><strong>A live loss was diagnosed to root cause, not rationalized.</strong> During 30 days of live paper trading (May–Jun 2026), the system lost -0.98% with a 39.66% winrate — far below the historically expected 74.22% for the same regime. Three hypotheses were tested and rejected with data: low volatility (ATR at 47th percentile), regime mismatch, and model drift. The true cause: low directional efficiency in 12h windows (std 1.433% vs.&nbsp;historical 4.968% in the same regime) combined with a model never retrained past April 2026. A retrain on the exact same calendar period returned +5.97% (winrate 67.07%). The ability to distinguish root cause from noise is the difference between a research process and a rationalization process.</p></li>
<li><p><strong>Risk-adjusted quality improves materially with regime filtering.</strong> The BULL_AND_HIGHVOL filter — validated across 5 independent layers (walk-forward causal, position sizing, Monte Carlo, SPA, retroactive live test) — lifts Sharpe from 0.64 to 0.85 and halves maximum drawdown from -14.4% to -7.4%. The filter is implemented causally: no future data is used in the regime classification at any point.</p></li>
<li><p><strong>Negative results are documented, not omitted.</strong> A full 16-cell regime matrix (4 trend categories × 4 volatility quartiles) was designed, tested against held-out 2025–2026 data, and rejected: all 16 cells produced Sharpe ≈ 0.75 — statistically indistinguishable from the unfiltered baseline (Sharpe 0.7456). On 1h candles, regime streaks last a median of 3 hours. On daily candles with 14-day smoothing, streaks stabilize to weeks but lose discriminatory power. The 16-cell approach was archived, not deployed.</p></li>
<li><p><strong>Production parity with backtest required explicit enforcement.</strong> Three bugs were found in the live deployment. The most consequential: a 6,000x scale error in the EV-gap filter caused the bot to reject ~100% of valid trades for 20 days — silently, without crashing. The root cause was a divergence between <code>walk.py</code> (backtest) and <code>s4_policy.py</code> (production): the same logical filter implemented with different units. Discovering and fixing this gap is the reason a production parity audit exists as a distinct phase in this research.</p></li>
<li><p><strong>Regular retraining is the single most important operational variable.</strong> Simulated performance Oct 2024 – Jul 2026 (21 months): <strong>+325.7%</strong> with MaxDD -0.60% and 77.0% winrate, vs.&nbsp;BTC buy-and-hold <strong>+1.0%</strong> in the same period. Positive across all market regimes including the $60k→$109k bull run. The only confirmed underperformance (-0.98%, May–Jun 2026) was caused by a model not retrained for 60+ days. Regime filters tested exhaustively and rejected. The retrain cadence (every 14 days) is the mechanism.</p></li>
<li><p><strong><code>p_up</code> is a ranking signal, not a calibrated probability.</strong> Isotonic Regression and Platt Scaling improve the Brier score but destroy F1 (0.269 → ~0.0000) by collapsing predictions toward the center. The model’s edge lives in the extremes of its score distribution. This limits Kelly-based sizing to conservative fractional variants and rules out probability-weighted portfolio construction until a calibration method that preserves the ranking structure is found.</p></li>
</ol>
</section>
<section id="how-to-read-this-report" class="level2">
<h2 class="anchored" data-anchor-id="how-to-read-this-report">How to Read This Report</h2>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Chapter</th>
<th>Content</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><a href="./01-architecture.html">1. Architecture</a></td>
<td>System design, decision engine, parameters</td>
</tr>
<tr class="even">
<td><a href="./02-statistical-due-diligence.html">2. Statistical Due Diligence</a></td>
<td>Full institutional audit (7 priorities)</td>
</tr>
<tr class="odd">
<td><a href="./03-regime-research.html">3. Regime Research</a></td>
<td>Meta-regime filter, Kelly sizing, matrix rejection</td>
</tr>
<tr class="even">
<td><a href="./04-live-validation.html">4. Live Validation</a></td>
<td>Production bugs, 30-day paper trading, root cause</td>
</tr>
<tr class="odd">
<td><a href="./05-deployment.html">5. Deployment</a></td>
<td>Railway, monitoring, operational parameters</td>
</tr>
<tr class="even">
<td><a href="./06-roadmap.html">6. Roadmap</a></td>
<td>Open gaps, prioritized</td>
</tr>
<tr class="odd">
<td><a href="./99-appendix-data-sources.html">Appendix</a></td>
<td>Data source reconciliation, full file inventory</td>
</tr>
</tbody>
</table>


<!-- -->

</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
  </div>
  <div class="nav-page nav-page-next">
      <a href="./01-architecture.html" class="pagination-link" aria-label="System Architecture">
        <span class="nav-page-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">System Architecture</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb1" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu"># Executive Summary {.unnumbered}</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">## What is S4</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>S4 is a systematic short-term trading engine for BTCUSDT Perpetual Futures, built on a structural mathematical edge in perpetual futures markets.</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>**The core mechanism:** with TP=2.0×ATR and SL=0.8×ATR, the geometric probability of a short winning in a random walk is 71.4%. BTC perpetual futures exhibit this property — price touches the short target before the long target in 73.5% of 1h candles historically. An EV-gap filter selects the highest-EV candidates each day. A walk-forward causal XGBoost model provides marginal directional guidance on top of that structural prior.</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>**Simulated result (Oct 2024 – Jul 2026, 21 months):** +325.7% vs. BTC hold +1.0%, MaxDD -0.60%, winrate 77.0%. Positive in all regimes tested including the $60k→$109k bull run.</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">## Current Classification</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; **"Research-grade promising systematic strategy."**</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; Not yet: institutional production system.</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; Substantially beyond: hobby backtesting.</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>Source: <span class="in">`statistics/README.md`</span>, Final Conclusions.</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; **Operational status (as of 28 Jul 2026):** Paper trading on Railway — live and running. Last retrain: 25 Jul 2026 (`retrain_pipeline.py`, automated, equity $8,830, winrate 64.44%). Railway Volume (`/app/persist`, 500 MB) — state, model, and ledger persist across redeploys. **Capital deployment decision pending: 27 Sep 2026** (3-month clean paper trading checkpoint).</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a><span class="fu">## Snapshot (last validated run — 26 Jun 2026 retrain)</span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>| Metric | Value | Source |</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>|---|---|---|</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>| Equity final (walk-forward, Jul 2026 retrain) | **$8,830** (baseline: $7,989; +10.5%) | <span class="in">`walk_summary.json`</span>, 25 Jul 2026 retrain |</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>| CAGR | **70.93%** | <span class="in">`walk_summary.json`</span>, 25 Jul 2026 retrain |</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>| Win rate (baseline, no regime filter) | **64.44%** | <span class="in">`walk_summary.json`</span>, 25 Jul 2026 retrain |</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>| Live performance (Oct 2024 – Jul 2026, 21 months) | **+325.7%** (winrate 77.0%, MaxDD -0.60%) | <span class="in">`r_and_d/02_pnl_attribution/`</span> |</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>| BTC hold same period | **+1.0%** | OKX BTCUSDT price |</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>| Win rate (BULL_AND_HIGHVOL filter) | 72.61% | <span class="in">`s4_enhancement/README.md`</span> |</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>| Sharpe-like (baseline) | 0.6395 | <span class="in">`statistics/whites_reality_check_report.csv`</span> |</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>| Sharpe-like (BULL_AND_HIGHVOL filter) | 0.8534 | <span class="in">`s4_enhancement/integrated_meta_walk_report.csv`</span> |</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>| Max Drawdown (daily) | -2.04% | <span class="in">`walk_summary.json`</span>, <span class="in">`statistics/README.md`</span> (consistent) |</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>| Max Drawdown (BULL_AND_HIGHVOL filter) | -7.40% | <span class="in">`s4_enhancement/README.md`</span> |</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>| 30-day live paper trading (real, May–Jun 2026) | -0.98% (winrate 39.66%) | <span class="in">`RESULTADO_MATRIZ_Y_CAUSA_30DIAS.md`</span> |</span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>| 30-day retroactive OOS retrain (same period) | +5.97% (winrate 67.07%) | <span class="in">`RESULTADO_MATRIZ_Y_CAUSA_30DIAS.md`</span> |</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>| Full Kelly estimate | 0.505 | <span class="in">`statistics/fractional_kelly_report.csv`</span> |</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>| White's Reality Check p-value | 0.506 (FAIL) | <span class="in">`statistics/whites_reality_check_report.csv`</span> |</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>| SPA sign-flip p-value | 0.000 (PASS) | <span class="in">`statistics/README.md`</span> |</span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a>Note: rows flagged "conflicting values" have two or more source documents reporting different numbers for the same metric. These are **not yet reconciled** — see the <span class="co">[</span><span class="ot">Appendix</span><span class="co">](99-appendix-data-sources.qmd)</span> for the full side-by-side and a note to revisit.</span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a><span class="fu">## Key Findings (validated, cross-checked)</span></span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**The edge is statistically real and survives adversarial testing.**</span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a>   A randomized-label sanity check — the most direct test for model</span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a>   memorization — collapses F1 from 0.218 to 0.014 and recall to 0.009</span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a>   when trade labels are shuffled. The model extracts genuine signal from</span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a>   price structure, not noise. SPA sign-flip p-value: 0.000 across all</span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a>   three market regimes (bear, lateral, bull) independently.</span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**The edge holds across market regimes — including bear markets.**</span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a>   S4 generates 4.9x–5.5x the return of a buy-and-hold benchmark in</span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a>   bear, lateral, and bull conditions simultaneously, each at p=0.000.</span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a>   This was the key result that elevated S4 from a bull-market artifact</span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a>   to a structurally robust strategy.</span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>**A live loss was diagnosed to root cause, not rationalized.**</span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a>   During 30 days of live paper trading (May–Jun 2026), the system lost</span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a>   -0.98% with a 39.66% winrate — far below the historically expected</span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a>   74.22% for the same regime. Three hypotheses were tested and rejected</span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a>   with data: low volatility (ATR at 47th percentile), regime mismatch,</span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a>   and model drift. The true cause: low directional efficiency in 12h</span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a>   windows (std 1.433% vs. historical 4.968% in the same regime) combined</span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a>   with a model never retrained past April 2026. A retrain on the exact</span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a>   same calendar period returned +5.97% (winrate 67.07%). The ability to</span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a>   distinguish root cause from noise is the difference between a research</span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a>   process and a rationalization process.</span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>**Risk-adjusted quality improves materially with regime filtering.**</span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a>   The BULL_AND_HIGHVOL filter — validated across 5 independent layers</span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a>   (walk-forward causal, position sizing, Monte Carlo, SPA, retroactive</span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a>   live test) — lifts Sharpe from 0.64 to 0.85 and halves maximum</span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a>   drawdown from -14.4% to -7.4%. The filter is implemented causally:</span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a>   no future data is used in the regime classification at any point.</span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span>**Negative results are documented, not omitted.**</span>
<span id="cb1-79"><a href="#cb1-79" aria-hidden="true" tabindex="-1"></a>   A full 16-cell regime matrix (4 trend categories × 4 volatility</span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a>   quartiles) was designed, tested against held-out 2025–2026 data, and</span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a>   rejected: all 16 cells produced Sharpe ≈ 0.75 — statistically</span>
<span id="cb1-82"><a href="#cb1-82" aria-hidden="true" tabindex="-1"></a>   indistinguishable from the unfiltered baseline (Sharpe 0.7456). On 1h</span>
<span id="cb1-83"><a href="#cb1-83" aria-hidden="true" tabindex="-1"></a>   candles, regime streaks last a median of 3 hours. On daily candles with</span>
<span id="cb1-84"><a href="#cb1-84" aria-hidden="true" tabindex="-1"></a>   14-day smoothing, streaks stabilize to weeks but lose discriminatory</span>
<span id="cb1-85"><a href="#cb1-85" aria-hidden="true" tabindex="-1"></a>   power. The 16-cell approach was archived, not deployed.</span>
<span id="cb1-86"><a href="#cb1-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-87"><a href="#cb1-87" aria-hidden="true" tabindex="-1"></a><span class="ss">6. </span>**Production parity with backtest required explicit enforcement.**</span>
<span id="cb1-88"><a href="#cb1-88" aria-hidden="true" tabindex="-1"></a>   Three bugs were found in the live deployment. The most consequential:</span>
<span id="cb1-89"><a href="#cb1-89" aria-hidden="true" tabindex="-1"></a>   a 6,000x scale error in the EV-gap filter caused the bot to reject</span>
<span id="cb1-90"><a href="#cb1-90" aria-hidden="true" tabindex="-1"></a>   ~100% of valid trades for 20 days — silently, without crashing.</span>
<span id="cb1-91"><a href="#cb1-91" aria-hidden="true" tabindex="-1"></a>   The root cause was a divergence between <span class="in">`walk.py`</span> (backtest) and</span>
<span id="cb1-92"><a href="#cb1-92" aria-hidden="true" tabindex="-1"></a>   <span class="in">`s4_policy.py`</span> (production): the same logical filter implemented with</span>
<span id="cb1-93"><a href="#cb1-93" aria-hidden="true" tabindex="-1"></a>   different units. Discovering and fixing this gap is the reason a</span>
<span id="cb1-94"><a href="#cb1-94" aria-hidden="true" tabindex="-1"></a>   production parity audit exists as a distinct phase in this research.</span>
<span id="cb1-95"><a href="#cb1-95" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-96"><a href="#cb1-96" aria-hidden="true" tabindex="-1"></a><span class="ss">8. </span>**Regular retraining is the single most important operational variable.**</span>
<span id="cb1-97"><a href="#cb1-97" aria-hidden="true" tabindex="-1"></a>   Simulated performance Oct 2024 – Jul 2026 (21 months): **+325.7%** with MaxDD -0.60% and 77.0% winrate, vs. BTC buy-and-hold **+1.0%** in the same period. Positive across all market regimes including the $60k→$109k bull run. The only confirmed underperformance (-0.98%, May–Jun 2026) was caused by a model not retrained for 60+ days. Regime filters tested exhaustively and rejected. The retrain cadence (every 14 days) is the mechanism.</span>
<span id="cb1-98"><a href="#cb1-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-99"><a href="#cb1-99" aria-hidden="true" tabindex="-1"></a><span class="ss">7. </span>**`p_up` is a ranking signal, not a calibrated probability.**</span>
<span id="cb1-100"><a href="#cb1-100" aria-hidden="true" tabindex="-1"></a>   Isotonic Regression and Platt Scaling improve the Brier score but</span>
<span id="cb1-101"><a href="#cb1-101" aria-hidden="true" tabindex="-1"></a>   destroy F1 (0.269 → ~0.0000) by collapsing predictions toward the</span>
<span id="cb1-102"><a href="#cb1-102" aria-hidden="true" tabindex="-1"></a>   center. The model's edge lives in the extremes of its score</span>
<span id="cb1-103"><a href="#cb1-103" aria-hidden="true" tabindex="-1"></a>   distribution. This limits Kelly-based sizing to conservative fractional</span>
<span id="cb1-104"><a href="#cb1-104" aria-hidden="true" tabindex="-1"></a>   variants and rules out probability-weighted portfolio construction until</span>
<span id="cb1-105"><a href="#cb1-105" aria-hidden="true" tabindex="-1"></a>   a calibration method that preserves the ranking structure is found.</span>
<span id="cb1-106"><a href="#cb1-106" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-107"><a href="#cb1-107" aria-hidden="true" tabindex="-1"></a><span class="fu">## How to Read This Report</span></span>
<span id="cb1-108"><a href="#cb1-108" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-109"><a href="#cb1-109" aria-hidden="true" tabindex="-1"></a>| Chapter | Content |</span>
<span id="cb1-110"><a href="#cb1-110" aria-hidden="true" tabindex="-1"></a>|---|---|</span>
<span id="cb1-111"><a href="#cb1-111" aria-hidden="true" tabindex="-1"></a>| <span class="co">[</span><span class="ot">1. Architecture</span><span class="co">](01-architecture.qmd)</span> | System design, decision engine, parameters |</span>
<span id="cb1-112"><a href="#cb1-112" aria-hidden="true" tabindex="-1"></a>| <span class="co">[</span><span class="ot">2. Statistical Due Diligence</span><span class="co">](02-statistical-due-diligence.qmd)</span> | Full institutional audit (7 priorities) |</span>
<span id="cb1-113"><a href="#cb1-113" aria-hidden="true" tabindex="-1"></a>| <span class="co">[</span><span class="ot">3. Regime Research</span><span class="co">](03-regime-research.qmd)</span> | Meta-regime filter, Kelly sizing, matrix rejection |</span>
<span id="cb1-114"><a href="#cb1-114" aria-hidden="true" tabindex="-1"></a>| <span class="co">[</span><span class="ot">4. Live Validation</span><span class="co">](04-live-validation.qmd)</span> | Production bugs, 30-day paper trading, root cause |</span>
<span id="cb1-115"><a href="#cb1-115" aria-hidden="true" tabindex="-1"></a>| <span class="co">[</span><span class="ot">5. Deployment</span><span class="co">](05-deployment.qmd)</span> | Railway, monitoring, operational parameters |</span>
<span id="cb1-116"><a href="#cb1-116" aria-hidden="true" tabindex="-1"></a>| <span class="co">[</span><span class="ot">6. Roadmap</span><span class="co">](06-roadmap.qmd)</span> | Open gaps, prioritized |</span>
<span id="cb1-117"><a href="#cb1-117" aria-hidden="true" tabindex="-1"></a>| <span class="co">[</span><span class="ot">Appendix</span><span class="co">](99-appendix-data-sources.qmd)</span> | Data source reconciliation, full file inventory |</span></code><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/erictvillarreal/RoboTrader812/edit/main/index.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/erictvillarreal/RoboTrader812/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer><script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>